config/routes.rb
    match '/:feed/request/:url_title' => 'track#track_request', :as => :track_request, :feed => /(track|feed)/
    match '/:feed/list/:view' => 'track#track_list', :as => :track_list, :view => nil, :feed => /(track|feed)/
    match '/:feed/body/:url_name' => 'track#track_public_body', :as => :track_public_body, :feed => /(track|feed)/
    match '/:feed/user/:url_name' => 'track#track_user', :as => :track_user, :feed => /(track|feed)/
    # TODO: :format doesn't work. See hacky code in the controller that makes up for this.
    match '/:feed/search/:query_array' => 'track#track_search_query',
          :as => :track_search,
          :feed => /(track|feed)/,
          :constraints => { :query_array => /.*/ }

    match '/track/update/:track_id' => 'track#update', :as => :update
    match '/track/delete_all_type' => 'track#delete_all_type', :as => :delete_all_type
    match '/track/feed/:track_id' => 'track#atom_feed', :as => :atom_feed
    ####

    #### Help controller
    match '/help/unhappy/:url_title' => 'help#unhappy', :as => :help_unhappy
    match '/help/about' => 'help#about', :as => :help_about
    match '/help/alaveteli' => 'help#alaveteli', :as => :help_alaveteli
    match '/help/contact' => 'help#contact', :as => :help_contact
    match '/help/officers' => 'help#officers', :as => :help_officers
    match '/help/requesting' => 'help#requesting', :as => :help_requesting
    match '/help/privacy' => 'help#privacy', :as => :help_privacy
    match '/help/api' => 'help#api', :as => :help_api
    match '/help/credits' => 'help#credits', :as => :help_credits
    match '/help/:action' => 'help#action', :as => :help_general
    match '/help' => 'help#index'
    ####

    #### Holiday controller
    match '/due_date/:holiday' => 'holiday#due_date', :as => :due_date
    ####

    #### RequestGame controller
    match '/categorise/play' => 'request_game#play', :as => :categorise_play
    match '/categorise/request/:url_title' => 'request_game#show', :as => :categorise_request
    match '/categorise/stop' => 'request_game#stop', :as => :categorise_stop
    ####

    #### AdminPublicBody controller
    match '/admin/missing_scheme' => 'admin_public_body#missing_scheme', :as => :admin_body_missing
    match '/admin/body' => 'admin_public_body#index', :as => :admin_body_index
    match '/admin/body/list' => 'admin_public_body#list', :as => :admin_body_list
    match '/admin/body/show/:id' => 'admin_public_body#show', :as => :admin_body_show
    match '/admin/body/new' => 'admin_public_body#new', :as => :admin_body_new
    match '/admin/body/edit/:id' => 'admin_public_body#edit', :as => :admin_body_edit
    match '/admin/body/update/:id' => 'admin_public_body#update', :as => :admin_body_update
    match '/admin/body/create' => 'admin_public_body#create', :as => :admin_body_create
    match '/admin/body/destroy/:id' => 'admin_public_body#destroy', :as => :admin_body_destroy
    match '/admin/body/import_csv' => 'admin_public_body#import_csv', :as => :admin_body_import_csv
    match '/admin/body/mass_tag_add' => 'admin_public_body#mass_tag_add', :as => :admin_body_mass_tag_add
    ####

    #### AdminPublicBodyCategory controller
    scope '/admin', :as => 'admin' do
        resources :categories,
                  :controller => 'admin_public_body_categories'
    end
    ####

    #### AdminPublicBodyHeading controller
    scope '/admin', :as => 'admin'  do
        resources :headings,
                  :controller => 'admin_public_body_headings',
                  :except => [:index] do
                      post 'reorder', :on => :collection
                      post 'reorder_categories', :on => :member
        end
    end
    ####

    #### AdminPublicBodyChangeRequest controller
    match '/admin/change_request/edit/:id' => 'admin_public_body_change_requests#edit', :as => :admin_change_request_edit
    match '/admin/change_request/update/:id' => 'admin_public_body_change_requests#update', :as => :admin_change_request_update
    ####

    #### AdminGeneral controller
    match '/admin' => 'admin_general#index', :as => :admin_general_index
    match '/admin/timeline' => 'admin_general#timeline', :as => :admin_timeline
    match '/admin/debug' => 'admin_general#debug', :as => :admin_debug
    match '/admin/stats' => 'admin_general#stats', :as => :admin_stats
    ####

    #### AdminRequest controller
    match '/admin/request' => 'admin_request#index', :as => :admin_request_index
    match '/admin/request/list' => 'admin_request#list', :as => :admin_request_list
    match '/admin/request/show/:id' => 'admin_request#show', :as => :admin_request_show
    match '/admin/request/resend' => 'admin_request#resend', :as => :admin_request_resend
    match '/admin/request/edit/:id' => 'admin_request#edit', :as => :admin_request_edit
    match '/admin/request/update/:id' => 'admin_request#update', :as => :admin_request_update
    match '/admin/request/destroy/:id' => 'admin_request#fully_destroy', :as => :admin_request_destroy
    match '/admin/request/edit_comment/:id' => 'admin_request#edit_comment', :as => :admin_request_edit_comment
    match '/admin/request/update_comment/:id' => 'admin_request#update_comment', :as => :admin_request_update_comment
    match '/admin/request/move_request' => 'admin_request#move_request', :as => :admin_request_move_request
    match '/admin/request/generate_upload_url/:id' => 'admin_request#generate_upload_url', :as => :admin_request_generate_upload_url
    match '/admin/request/show_raw_email/:id' => 'admin_request#show_raw_email', :as => :admin_request_show_raw_email
    match '/admin/request/download_raw_email/:id' => 'admin_request#download_raw_email', :as => :admin_request_download_raw_email
    match '/admin/request/mark_event_as_clarification' => 'admin_request#mark_event_as_clarification', :as => :admin_request_clarification
    match '/admin/request/hide/:id' => 'admin_request#hide_request', :as => :admin_request_hide
    ####

    #### AdminIncomingMessage controller
    match '/admin/incoming/destroy' => 'admin_incoming_message#destroy', :as => :admin_incoming_destroy
    match '/admin/incoming/redeliver' => 'admin_incoming_message#redeliver', :as => :admin_incoming_redeliver
    match '/admin/incoming/edit/:id' => 'admin_incoming_message#edit', :as => :admin_incoming_edit
    match '/admin/incoming/update/:id' => 'admin_incoming_message#update', :as => :admin_incoming_update
    ####

    #### AdminOutgoingMessage controller
    match '/admin/outgoing/edit/:id' => 'admin_outgoing_message#edit', :as => :admin_outgoing_edit
    match '/admin/outgoing/destroy/:id' => 'admin_outgoing_message#destroy', :as => :admin_outgoing_destroy
    match '/admin/outgoing/update/:id' => 'admin_outgoing_message#update', :as => :admin_outgoing_update
    ####

    #### AdminUser controller
    match '/admin/user' => 'admin_user#index', :as => :admin_user_index
    match '/admin/user/list' => 'admin_user#list', :as => :admin_user_list
    match '/admin/user/banned' => 'admin_user#list_banned', :as => :admin_user_list_banned
    match '/admin/user/show/:id' => 'admin_user#show', :as => :admin_user_show
    match '/admin/user/edit/:id' => 'admin_user#edit', :as => :admin_user_edit
    match '/admin/user/show_bounce_message/:id' => 'admin_user#show_bounce_message', :as => :admin_user_show_bounce
    match '/admin/user/update/:id' => 'admin_user#update', :as => :admin_user_update
    match '/admin/user/clear_bounce/:id' => 'admin_user#clear_bounce', :as => :admin_user_clear_bounce
    match '/admin/user/destroy_track' => 'admin_user#destroy_track', :as => :admin_user_destroy_track
    match '/admin/user/login_as/:id' => 'admin_user#login_as', :as => :admin_user_login_as
    match '/admin/user/clear_profile_photo/:id' => 'admin_user#clear_profile_photo', :as => :admin_clear_profile_photo
    match '/admin/user/modify_comment_visibility/:id' => 'admin_user#modify_comment_visibility', :as => 'admin_user_modify_comment_visibility'
    ####

    #### AdminTrack controller
    match '/admin/track/list' => 'admin_track#list', :as => :admin_track_list
    ####

    #### AdminCensorRule controller
    match '/admin/censor/new' => 'admin_censor_rule#new', :as => :admin_rule_new
    match '/admin/censor/create' => 'admin_censor_rule#create', :as => :admin_rule_create
    match '/admin/censor/edit/:id' => 'admin_censor_rule#edit', :as => :admin_rule_edit
    match '/admin/censor/update/:id' => 'admin_censor_rule#update', :as => :admin_rule_update
    match '/admin/censor/destroy/:censor_rule_id' => 'admin_censor_rule#destroy', :as => :admin_rule_destroy

    scope '/admin', :as => 'admin' do
        resources :info_requests, :only => [] do
            resources :censor_rules,
                      :controller => 'admin_censor_rule',
                      :only => [:new, :create],
                      :name_prefix => 'info_request_'
        end
    end

    scope '/admin', :as => 'admin' do
        resources :users, :only => [] do
            resources :censor_rules,
                      :controller => 'admin_censor_rule',
                      :only => [:new, :create],
                      :name_prefix => 'user_'
        end
    end
    ####

    #### AdminSpamAddresses controller
    scope '/admin', :as => 'admin' do
        resources :spam_addresses,
                  :controller => 'admin_spam_addresses',
                  :only => [:index, :create, :destroy]
    end
    ####

    #### Api controller
    match '/api/v2/request.json' => 'api#create_request', :as => :api_create_request, :via => :post

    match '/api/v2/request/:id.json' => 'api#show_request', :as => :api_show_request, :via => :get
    match '/api/v2/request/:id.json' => 'api#add_correspondence', :as => :api_add_correspondence, :via => :post
    match '/api/v2/request/:id/update.json' => 'api#update_state', :as => :api_update_state, :via => :post

app/views/admin_request/_incoming_message_actions.html.erb
<fieldset class="form-horizontal">
 <legend>Actions</legend>
 <%= form_tag admin_incoming_redeliver_path, :class => "form form-inline" do %>
 <div class="control-group">
  <label class="control-label" for="url_title_<%= incoming_message.id %>">Redeliver message to one or more other requests</label>
  <div class="controls">
      <% if @info_requests && @info_requests.size == 1 %>
        <%= text_field_tag 'url_title', @info_requests[0].url_title, { :size => 20, :id => "url_title_#{incoming_message.id}" } %>
      <% else %>
        <%= text_field_tag 'url_title', "", { :size => 20, :id => "url_title_#{incoming_message.id}" } %>
      <% end %>
      <%= hidden_field_tag 'redeliver_incoming_message_id', incoming_message.id, :id => nil %>
      <%= submit_tag "Redeliver to another request", :class => "btn" %>
      <p class="help-block"><code>id</code> or <code>url_title</code>; you can supply more than one, separated by commas</p>
  </div>
 </div>
 <% end %>
 <div class="control-group">
  <label class="control-label">Generate FOI officer upload URL</label>
  <div class="controls">
   <%= link_to 'Generate and take me there', admin_request_generate_upload_url_path(incoming_message.info_request, :incoming_message_id => incoming_message.id), :class => "btn" %>
  </div>
 </div>

  <div class="control-group">
    <label class="control-label">Mark <code>To:</code> address as spam</label>
    <div class="controls">
      <%= link_to 'Spam Addresses', admin_spam_addresses_path %>
    </div>
  </div>

 <%= form_tag admin_incoming_destroy_path, :class => "form form-inline" do %>
  <div class="control-group">
   <label class="control-label" for="destroy_message_<%= incoming_message.id %>">Destroy message</label>
   <div class="controls">
    <%= hidden_field_tag 'incoming_message_id', incoming_message.id, :id => nil %>
    <%= submit_tag "Destroy message", :class => "btn btn-danger", :confirm => "This is permanent! Are you sure?", :id => "destroy_message_#{incoming_message.id}" %>
   </div>
  </div>
 <% end %>

 <% if @raw_email.nil? %>
  <%# we're not on the raw_email page itself %>
  <div class="control-group">
   <label class="control-label">Inspect email</label>
   <div class="controls">
     <%= link_to "View raw email", admin_request_show_raw_email_path(incoming_message.raw_email_id), :class => "btn" %>
   </div>
  </div>
 <% end %>

</fieldset>

app/views/admin_request/_some_annotations.html.erb
<% if comments.any? %>
  <%= form_tag admin_user_modify_comment_visibility_path do %>
    <div class="accordion" id="comments">
      <% comments.each do |comment| %>
        <div class="accordion-group">
          <div class="accordion-heading">
            <%= check_box_tag 'comment_ids[]', comment.id %>
  
            <a href="#comment_<%= comment.id %>" data-toggle="collapse" data-parent="#comments"><%= chevron_right %></a>
  
            <%= link_to admin_request_edit_comment_path(comment) do %>
              #<%= comment.id %>
              --
              <%= h(comment.user.name) %>
              <%= admin_value(comment.created_at) %>
            <% end %>
  
            <%= comment_visibility(comment) %>

            <blockquote class="incoming-message">
              <%= truncate(comment.body, :length => 400) %>
            </blockquote>
          </div>

          <div id="comment_<%= comment.id %>" class="accordion-body collapse">
            <table class="table table-striped table-condensed">
              <tbody>
                <tr>
                  <td colspan="2">
                    By <%= user_both_links(comment.user) %>
                  </td>
                </tr>
                <% comment.for_admin_column do |name, value, type, column_name |%>
                  <tr>
                    <td>
                      <b><%= name %></b>
                    </td>
                    <td>
                      <% if column_name == 'body' && !comment.visible %>
                        <s><%= h comment.send(column_name) %></s>
                      <% else %>
                        <%= h comment.send(column_name) %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        </div>
      <% end %>
    </div>

    <%= submit_tag 'Hide selected', :name => 'hide_selected' %>
    <%= submit_tag 'Unhide selected', :name => 'unhide_selected' %>

  <% end %>
<% else %>
  <p>None yet.</p>
<% end %> 

app/views/admin_request/_some_requests.html.erb
<div class="accordion" id="requests">
  <% for info_request in info_requests %>
    <div class="accordion-group">
      <div class="accordion-heading accordion-toggle row">
        <span class="item-title span6">
          <a href="#request_<%=info_request.id%>" data-toggle="collapse" data-parent="requests"><%= chevron_right %></a>
          <%= link_to(info_request.title, admin_request_show_path(info_request), :title => "view full details") %>
        </span>
        <span class="item-metadata span6">
          <%= user_admin_link_for_request(info_request) %> <%= arrow_right %> <%= link_to("#{info_request.public_body.name}", admin_body_show_path(info_request.public_body)) %>, <%= time_ago_in_words(info_request.updated_at) %> ago
        </span>
      </div>
      <div id="request_<%=info_request.id%>" class="item-detail accordion-body collapse row">
        <% info_request.for_admin_column do | name, value, type | %>
          <div>
            <span class="span6">
              <%= h name %>
            </span>
            <span class="span6">
              <% if type == 'datetime' %>
                <%= I18n.l(value, :format => "%e %B %Y %H:%M:%S") %>
                (<%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(value)) %>)
              <% else %>
                <%=h value %>
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin_request/_tags.html.erb
<% for t in info_request.tags %>
    <% if t.value %>
        <%=h t.name %>:<%=h t.value %>
    <% else %>
        <%=h t.name %>
    <% end %>
<% end %>

app/views/admin_request/edit.html.erb
<h1>Edit basic details of request</h1>

<%= error_messages_for 'info_request' %>

<%= form_tag admin_request_update_path(@info_request) do %>

   <p><label for="info_request_title"><strong>Title</strong></label> (warning: editing this will break URLs right now)<br/>
   <%= text_field 'info_request', 'title', :size => 50  %></p>

   <p><label for="info_request_prominence"><strong>Prominence</strong></label>
   <%= select( 'info_request', "prominence", [ "normal", "backpage", "requester_only", "hidden" ]) %>
   (backpage means hidden from lists/search; hidden means completely hidden; super users can see anything)
   </p>

   <p>
   <label for="info_request_allow_new_responses_from"><strong>Allow new responses</strong> from</label>
   <%= select( 'info_request', "allow_new_responses_from", [ "anybody", "authority_only", "nobody" ] ) %>;
   <label for="info_request_handle_rejected_responses"><strong>Handle rejected responses</strong> with</label>
   <%= select( 'info_request', "handle_rejected_responses", [ "bounce", "holding_pen", "blackhole" ] ) %>
   <br>
   ('authority_only' means email From: domain of authority request email or any domain that has previously sent a response; 'nobody' also stops requester making followups; take care when using 'blackhole' which just drops mail)
   </p>

   <p><label for="info_request_described_state"><strong>Described state</strong></label>
   <%= select( 'info_request', "described_state", InfoRequest.enumerate_states) %>
    <label for="info_request_awaiting_description"><strong>Awaiting description</strong></label>
   <%= select('info_request', "awaiting_description", [["Yes – needs state updating",true],["No – state is up to date",false]]) %>
   <br/>(don't forget to change 'awaiting description' when you set described state)<br/>
   </p>
    <p><label for="info_request_comments_allowed"><strong>Are comments allowed?</strong></label>
    <%= select('info_request', "comments_allowed", [["Yes – comments allowed", true], ["No – comments disabled", false]]) %>
    </p>
   <p><label for="info_request_tag_string"><strong>Tags</strong> <small>(space separated, can use key:value)</small></label><br/>
   <%= text_field 'info_request', 'tag_string', :size => 60  %></p>

   <p><%= submit_tag 'Save changes', :accesskey => 's', :class => 'btn btn-primary' %>
   </p>

  <p><strong>Note:</strong> To edit the actual request body text, click edit
  next to the specific outgoing message.
  </p>

<% end %>

<p>
<%= link_to 'Show', admin_request_show_path(@info_request) %> |
<%= link_to 'List all', admin_request_list_path %>
</p>

<hr>

<div class="well">

<%= form_tag admin_request_destroy_path(@info_request) do %>
    <p>
    <strong>This is permanent and irreversible!</strong> <%= submit_tag 'Destroy request entirely', :class => 'btn btn-danger' %>
    <br>Use it mainly if someone posts private information, e.g. made a Data Protection request. It
    destroys all responses and tracks as well.
    </p>

<% end %>

</div>

<hr>

app/views/admin_request/edit_comment.html.erb
<h1>Edit annotation</h1>

<%= error_messages_for 'comment' %>

<%= form_tag admin_request_update_comment_path(@comment) do %>

   <p><label for="comment_body">Body of annotation</label><br/>
   <%= text_area 'comment', 'body', :rows => 10, :cols => 60  %></p>

   <p><label for="comment_visible">Visible</label> 
   <%= select('comment', "visible", [["Yes – show comment",true],["No – hide comment",false]]) %>
   </p>


  <p><%= submit_tag 'Save', :accesskey => 's' %></p>
<% end %>

<p>
<%= link_to 'Show', admin_request_show_path(@comment.info_request) %> |
<%= link_to 'List all', admin_request_list_path %>
</p>

app/views/admin_request/hidden_user_explanation.html.erb
<%= _("Dear {{name}},", :name => name_to) %>

<%= _("Your request '{{request}}' at {{url}} has been reviewed by moderators.", :request => info_request.title.html_safe, :url => info_request_url) %>

<%= reason == 'not_foi' ? _("We consider it is not a valid FOI request, and have therefore hidden it from other users.") : _("We consider it to be vexatious, and have therefore hidden it from other users.") %> <%= _("You will still be able to view it while logged in to the site. Please reply to this email if you would like to discuss this decision further.") %>

<%= _("Yours,") %>

<%= _("The {{site_name}} team.", :site_name => site_name) %>

app/views/admin_request/list.html.erb
<% @title = _("Listing FOI requests") %>

<h1><%=@title%></h1>

<%= form_tag({}, :method => "get", :class => "form form-search") do %>
  <%= text_field_tag 'query', params[:query], { :size => 30, :class => "input-large search-query" } %>
  <%= submit_tag "Search", :class => "btn" %> (substring search, titles only)
<% end %>

<%= render :partial => 'some_requests', :locals => { :info_requests => @info_requests } %>

<%= will_paginate(@info_requests, :class => "paginator") %>

app/views/admin_request/show_raw_email.html.erb
<%= render :partial => 'admin_incoming_message/intro', :locals => { :incoming_message => @raw_email.incoming_message } %>

    <% if @holding_pen %>
        <br>This is in the holding pen because: <strong><%= @rejected_reason %></strong>
        <% if @public_bodies.size > 0 %>
            <br>Guessed authority:
            <% @public_bodies.each do |public_body| %>
                <%=public_body_both_links(public_body)%>
            <% end %>
            (based on From: email domain)
        <% end %>
        <% if @info_requests.size > 0 %>
            <div class="accordion" id="guessed-requests">
                Guessed request:
                <% @info_requests.each do |info_request|  %>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a href="#info_request_<%= info_request.id %>" data-toggle="collapse"><i class="icon-chevron-right"></i></a>
                            <%=request_both_links(info_request)%>
                        </div>
                        <div class="accordion-body collapse" id="info_request_<%= info_request.id %>">
                            <table class="table table-striped table-condensed">
                                <tr>
                                    <td><strong>Last outgoing message:</strong></td>
                                    <td><%= info_request.outgoing_messages.last.body %></td>
                                </tr>
                                <tr>
                                    <td><strong>Created by:</strong></td>
                                    <td><%= user_admin_link_for_request(info_request) %></td>
                                </tr>
                                <tr>
                                    <td><strong>Authority:</strong></td>
                                    <td>
                                        <%= link_to(info_request.public_body.name, admin_body_show_path(info_request.public_body)) %>
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>url_title:</strong></td>
                                    <td><%= info_request.url_title %></td>
                                </tr>
                            </table>
                            <p>
                                This request was guessed because it has an incoming email address of <strong><%= info_request.incoming_email %></strong> and this incoming message was sent to <strong><%= @raw_email.incoming_message.mail.to %></strong>.
                            </p>
                        </div>
                    </div>
                <% end %>
                (based on id, not hash, in To/Cc email)
            </div>
        <% end %>
    <% end %>
</p>

<div>
    <%= render :partial => 'incoming_message_actions', :locals => { :incoming_message => @raw_email.incoming_message } %>
</div>

<h2>Raw email</h2>

<p><%= link_to "Download", admin_request_download_raw_email_path(@raw_email) %></p>

<pre><%=h(@raw_email.data).gsub(/\n/, '<br>').html_safe %></pre>