config/routes.rb
    match '/:feed/request/:url_title' => 'track#track_request', :as => :track_request, :feed => /(track|feed)/
    match '/:feed/list/:view' => 'track#track_list', :as => :track_list, :view => nil, :feed => /(track|feed)/
    match '/:feed/body/:url_name' => 'track#track_public_body', :as => :track_public_body, :feed => /(track|feed)/
    match '/:feed/user/:url_name' => 'track#track_user', :as => :track_user, :feed => /(track|feed)/
    # TODO: :format doesn't work. See hacky code in the controller that makes up for this.
    match '/:feed/search/:query_array' => 'track#track_search_query',
          :as => :track_search,
          :feed => /(track|feed)/,
          :constraints => { :query_array => /.*/ }

    match '/track/update/:track_id' => 'track#update', :as => :update
    match '/track/delete_all_type' => 'track#delete_all_type', :as => :delete_all_type
    match '/track/feed/:track_id' => 'track#atom_feed', :as => :atom_feed
    ####

    #### Help controller
    match '/help/unhappy/:url_title' => 'help#unhappy', :as => :help_unhappy
    match '/help/about' => 'help#about', :as => :help_about
    match '/help/alaveteli' => 'help#alaveteli', :as => :help_alaveteli
    match '/help/contact' => 'help#contact', :as => :help_contact
    match '/help/officers' => 'help#officers', :as => :help_officers
    match '/help/requesting' => 'help#requesting', :as => :help_requesting
    match '/help/privacy' => 'help#privacy', :as => :help_privacy
    match '/help/api' => 'help#api', :as => :help_api
    match '/help/credits' => 'help#credits', :as => :help_credits
    match '/help/:action' => 'help#action', :as => :help_general
    match '/help' => 'help#index'
    ####

    #### Holiday controller
    match '/due_date/:holiday' => 'holiday#due_date', :as => :due_date
    ####

    #### RequestGame controller
    match '/categorise/play' => 'request_game#play', :as => :categorise_play
    match '/categorise/request/:url_title' => 'request_game#show', :as => :categorise_request
    match '/categorise/stop' => 'request_game#stop', :as => :categorise_stop
    ####

    #### AdminPublicBody controller
    match '/admin/missing_scheme' => 'admin_public_body#missing_scheme', :as => :admin_body_missing
    match '/admin/body' => 'admin_public_body#index', :as => :admin_body_index
    match '/admin/body/list' => 'admin_public_body#list', :as => :admin_body_list
    match '/admin/body/show/:id' => 'admin_public_body#show', :as => :admin_body_show
    match '/admin/body/new' => 'admin_public_body#new', :as => :admin_body_new
    match '/admin/body/edit/:id' => 'admin_public_body#edit', :as => :admin_body_edit
    match '/admin/body/update/:id' => 'admin_public_body#update', :as => :admin_body_update
    match '/admin/body/create' => 'admin_public_body#create', :as => :admin_body_create
    match '/admin/body/destroy/:id' => 'admin_public_body#destroy', :as => :admin_body_destroy
    match '/admin/body/import_csv' => 'admin_public_body#import_csv', :as => :admin_body_import_csv
    match '/admin/body/mass_tag_add' => 'admin_public_body#mass_tag_add', :as => :admin_body_mass_tag_add
    ####

    #### AdminPublicBodyCategory controller
    scope '/admin', :as => 'admin' do
        resources :categories,
                  :controller => 'admin_public_body_categories'
    end
    ####

    #### AdminPublicBodyHeading controller
    scope '/admin', :as => 'admin'  do
        resources :headings,
                  :controller => 'admin_public_body_headings',
                  :except => [:index] do
                      post 'reorder', :on => :collection
                      post 'reorder_categories', :on => :member
        end
    end
    ####

    #### AdminPublicBodyChangeRequest controller
    match '/admin/change_request/edit/:id' => 'admin_public_body_change_requests#edit', :as => :admin_change_request_edit
    match '/admin/change_request/update/:id' => 'admin_public_body_change_requests#update', :as => :admin_change_request_update
    ####

    #### AdminGeneral controller
    match '/admin' => 'admin_general#index', :as => :admin_general_index
    match '/admin/timeline' => 'admin_general#timeline', :as => :admin_timeline
    match '/admin/debug' => 'admin_general#debug', :as => :admin_debug
    match '/admin/stats' => 'admin_general#stats', :as => :admin_stats
    ####

    #### AdminRequest controller
    match '/admin/request' => 'admin_request#index', :as => :admin_request_index
    match '/admin/request/list' => 'admin_request#list', :as => :admin_request_list
    match '/admin/request/show/:id' => 'admin_request#show', :as => :admin_request_show
    match '/admin/request/resend' => 'admin_request#resend', :as => :admin_request_resend
    match '/admin/request/edit/:id' => 'admin_request#edit', :as => :admin_request_edit
    match '/admin/request/update/:id' => 'admin_request#update', :as => :admin_request_update
    match '/admin/request/destroy/:id' => 'admin_request#fully_destroy', :as => :admin_request_destroy
    match '/admin/request/edit_comment/:id' => 'admin_request#edit_comment', :as => :admin_request_edit_comment
    match '/admin/request/update_comment/:id' => 'admin_request#update_comment', :as => :admin_request_update_comment
    match '/admin/request/move_request' => 'admin_request#move_request', :as => :admin_request_move_request
    match '/admin/request/generate_upload_url/:id' => 'admin_request#generate_upload_url', :as => :admin_request_generate_upload_url
    match '/admin/request/show_raw_email/:id' => 'admin_request#show_raw_email', :as => :admin_request_show_raw_email
    match '/admin/request/download_raw_email/:id' => 'admin_request#download_raw_email', :as => :admin_request_download_raw_email
    match '/admin/request/mark_event_as_clarification' => 'admin_request#mark_event_as_clarification', :as => :admin_request_clarification
    match '/admin/request/hide/:id' => 'admin_request#hide_request', :as => :admin_request_hide
    ####

    #### AdminIncomingMessage controller
    match '/admin/incoming/destroy' => 'admin_incoming_message#destroy', :as => :admin_incoming_destroy
    match '/admin/incoming/redeliver' => 'admin_incoming_message#redeliver', :as => :admin_incoming_redeliver
    match '/admin/incoming/edit/:id' => 'admin_incoming_message#edit', :as => :admin_incoming_edit
    match '/admin/incoming/update/:id' => 'admin_incoming_message#update', :as => :admin_incoming_update
    ####

    #### AdminOutgoingMessage controller
    match '/admin/outgoing/edit/:id' => 'admin_outgoing_message#edit', :as => :admin_outgoing_edit
    match '/admin/outgoing/destroy/:id' => 'admin_outgoing_message#destroy', :as => :admin_outgoing_destroy
    match '/admin/outgoing/update/:id' => 'admin_outgoing_message#update', :as => :admin_outgoing_update
    ####

    #### AdminUser controller
    match '/admin/user' => 'admin_user#index', :as => :admin_user_index
    match '/admin/user/list' => 'admin_user#list', :as => :admin_user_list
    match '/admin/user/banned' => 'admin_user#list_banned', :as => :admin_user_list_banned
    match '/admin/user/show/:id' => 'admin_user#show', :as => :admin_user_show
    match '/admin/user/edit/:id' => 'admin_user#edit', :as => :admin_user_edit
    match '/admin/user/show_bounce_message/:id' => 'admin_user#show_bounce_message', :as => :admin_user_show_bounce
    match '/admin/user/update/:id' => 'admin_user#update', :as => :admin_user_update
    match '/admin/user/clear_bounce/:id' => 'admin_user#clear_bounce', :as => :admin_user_clear_bounce
    match '/admin/user/destroy_track' => 'admin_user#destroy_track', :as => :admin_user_destroy_track
    match '/admin/user/login_as/:id' => 'admin_user#login_as', :as => :admin_user_login_as
    match '/admin/user/clear_profile_photo/:id' => 'admin_user#clear_profile_photo', :as => :admin_clear_profile_photo
    match '/admin/user/modify_comment_visibility/:id' => 'admin_user#modify_comment_visibility', :as => 'admin_user_modify_comment_visibility'
    ####

    #### AdminTrack controller
    match '/admin/track/list' => 'admin_track#list', :as => :admin_track_list
    ####

    #### AdminCensorRule controller
    match '/admin/censor/new' => 'admin_censor_rule#new', :as => :admin_rule_new
    match '/admin/censor/create' => 'admin_censor_rule#create', :as => :admin_rule_create
    match '/admin/censor/edit/:id' => 'admin_censor_rule#edit', :as => :admin_rule_edit
    match '/admin/censor/update/:id' => 'admin_censor_rule#update', :as => :admin_rule_update
    match '/admin/censor/destroy/:censor_rule_id' => 'admin_censor_rule#destroy', :as => :admin_rule_destroy

    scope '/admin', :as => 'admin' do
        resources :info_requests, :only => [] do
            resources :censor_rules,
                      :controller => 'admin_censor_rule',
                      :only => [:new, :create],
                      :name_prefix => 'info_request_'
        end
    end

    scope '/admin', :as => 'admin' do
        resources :users, :only => [] do
            resources :censor_rules,
                      :controller => 'admin_censor_rule',
                      :only => [:new, :create],
                      :name_prefix => 'user_'
        end
    end
    ####

    #### AdminSpamAddresses controller
    scope '/admin', :as => 'admin' do
        resources :spam_addresses,
                  :controller => 'admin_spam_addresses',
                  :only => [:index, :create, :destroy]
    end
    ####

    #### Api controller
    match '/api/v2/request.json' => 'api#create_request', :as => :api_create_request, :via => :post

    match '/api/v2/request/:id.json' => 'api#show_request', :as => :api_show_request, :via => :get
    match '/api/v2/request/:id.json' => 'api#add_correspondence', :as => :api_add_correspondence, :via => :post
    match '/api/v2/request/:id/update.json' => 'api#update_state', :as => :api_update_state, :via => :post

app/controllers/admin_general_controller.rb
# app/controllers/admin_controller.rb:
# Controller for main admin pages.
#
# Copyright (c) 2007 UK Citizens Online Democracy. All rights reserved.
# Email: hello@mysociety.org; WWW: http://www.mysociety.org/

class AdminGeneralController < AdminController

    def index
        # Overview counts of things
        @public_body_count = PublicBody.count

        @info_request_count = InfoRequest.count
        @outgoing_message_count = OutgoingMessage.count
        @incoming_message_count = IncomingMessage.count

        @user_count = User.count
        @track_thing_count = TrackThing.count

        @comment_count = Comment.count

        # Tasks to do
        @requires_admin_requests = InfoRequest.find_in_state('requires_admin')
        @error_message_requests = InfoRequest.find_in_state('error_message')
        @attention_requests = InfoRequest.find_in_state('attention_requested')
        @blank_contacts = PublicBody.find(:all, :conditions => ["request_email = ''"],
                                                :order => "updated_at")
        @old_unclassified = InfoRequest.find_old_unclassified(:limit => 20,
                                                              :conditions => ["prominence = 'normal'"])
        @holding_pen_messages = InfoRequest.holding_pen_request.incoming_messages
        @new_body_requests = PublicBodyChangeRequest.new_body_requests.open
        @body_update_requests = PublicBodyChangeRequest.body_update_requests.open
    end

    def timeline
        # Recent events
        @events_title = "Events in last two days"
        date_back_to = Time.now - 2.days
        if params[:hour]
            @events_title = "Events in last hour"
            date_back_to = Time.now - 1.hour
        end
        if params[:day]
            @events_title = "Events in last day"
            date_back_to = Time.now - 1.day
        end
        if params[:week]
            @events_title = "Events in last week"
            date_back_to = Time.now - 1.week
        end
        if params[:month]
            @events_title = "Events in last month"
            date_back_to = Time.now - 1.month
        end
        if params[:all]
            @events_title = "Events, all time"
            date_back_to = Time.now - 1000.years
        end

        # Get an array of event attributes within the timespan in the format
        # [id, type_of_model, event_timestamp]
        # Note that the relevent date for InfoRequestEvents is creation, but
        # for PublicBodyVersions is update thoughout
        connection = InfoRequestEvent.connection
        timestamps = connection.select_rows("SELECT id,'InfoRequestEvent',
                                                    created_at AS timestamp
                                             FROM info_request_events
                                             WHERE created_at > '#{date_back_to.getutc}'
                                             UNION
                                             SELECT id, 'PublicBodyVersion',
                                                  updated_at AS timestamp
                                             FROM #{PublicBody.versioned_class.table_name}
                                             WHERE updated_at > '#{date_back_to.getutc}'
                                             ORDER by timestamp desc")
        @events = WillPaginate::Collection.create((params[:page] or 1), 100) do |pager|
            # create a hash for each model type being returned
            info_request_event_ids = {}
            public_body_version_ids = {}
            # get the relevant slice from the paginator
            timestamps.slice(pager.offset, pager.per_page).each_with_index do |event, index|
                # for each event in the slice, add an item to the hash for the model type
                # whose key is the model id, and value is the position in the slice
                if event[1] == 'InfoRequestEvent'
                    info_request_event_ids[event[0].to_i] = index
                else
                    public_body_version_ids[event[0].to_i] = index
                end
            end
            # get all the models in the slice, eagerly loading the associations we use in the view
            public_body_versions = PublicBody.versioned_class.find(:all,
                                          :conditions => ['id in (?)', public_body_version_ids.keys],
                                          :include => [ { :public_body => :translations }])
            info_request_events = InfoRequestEvent.find(:all,
                                          :conditions => ['id in (?)', info_request_event_ids.keys],
                                          :include => [:info_request])
            @events = []
            # drop the models into a combined array, ordered by their position in the timestamp slice
            public_body_versions.each do |version|
                @events[public_body_version_ids[version.id]] = [version, version.updated_at]
            end
            info_request_events.each do |event|
                @events[info_request_event_ids[event.id]] = [event, event.created_at]
            end

            # inject the result array into the paginated collection:
            pager.replace(@events)

            # set the total entries for the page to the overall number of results
            pager.total_entries = timestamps.size
        end

    end

    def stats
        # Overview counts of things
        @public_body_count = PublicBody.count

        @info_request_count = InfoRequest.count
        @outgoing_message_count = OutgoingMessage.count
        @incoming_message_count = IncomingMessage.count

        @user_count = User.count
        @track_thing_count = TrackThing.count

        @comment_count = Comment.count
        @request_by_state = InfoRequest.count(:group => 'described_state')
        @tracks_by_type = TrackThing.count(:group => 'track_type')
    end

    def debug
        @admin_current_user = admin_current_user
        @current_commit = alaveteli_git_commit
        @current_branch = `git branch | perl -ne 'print $1 if /^\\* (.*)/'`
        @current_version = `git describe --always --tags`
        repo = `git remote show origin -n | perl -ne 'print $1 if m{Fetch URL: .*github\\.com[:/](.*)\\.git}'`
        @github_origin = "https://github.com/#{repo}/tree/"
        @request_env = request.env
    end

end

app/views/admin_general/_admin_navbar.html.erb
<div class="admin">
  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Alaveteli', frontpage_path, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to 'Summary', admin_general_index_path %></li>
            <li><%= link_to 'Timeline', admin_timeline_path %></li>
            <li><%= link_to 'Stats', admin_stats_path %></li>
            <li><%= link_to 'Debug', admin_debug_path %></li>
            <li><%= link_to 'Authorities', admin_body_list_path %></li>
            <li><%= link_to 'Categories', admin_categories_path %></li>
            <li><%= link_to 'Requests', admin_request_list_path %></li>
            <li><%= link_to 'Users', admin_user_list_path %></li>
            <li><%= link_to 'Tracks', admin_track_list_path %></li>
            <li><%= link_to 'Log out', signout_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin_general/index.html.erb
<% @title = "Summary" %>

<div class="row">
  <div class="span12">
    <h1><%=@title%></h1>

    <ul>
      <li><%=@public_body_count%> public authorities</li>
      <li>
        <%=@info_request_count%> requests, <%=@outgoing_message_count%> outgoing messages,
        <%=@incoming_message_count%> incoming messages
      </li>
      <li><%=@user_count%> users, <%=@track_thing_count%> tracked things</li>
      <li><%=@comment_count%> annotations</li>
    </ul>
  </div>
</div>

<hr>

<div class="row">
  <div class="span12">
    <h1>Things to do</h1>
  </div>
</div>

<div class="accordion" id="things-to-do">
  <% if @holding_pen_messages.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#holding-pen" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@holding_pen_messages.size%></span><%= chevron_right %> Put misdelivered responses with the right request</a>
      </div>
      <div id="holding-pen" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for message in @holding_pen_messages %>
              <tr>
                <td>
                  <% if message.get_body_for_quoting.strip.size == 0 %>
                      <%= link_to "(no body)", admin_request_show_raw_email_path(message.raw_email_id) %>
                  <% else %>
                      <%= link_to excerpt(message.get_body_for_quoting, "", :radius => 60), admin_request_show_raw_email_path(message.raw_email_id) %>
                  <% end %>
                </td>
                <td class="span2">
                  <%=simple_date(message.sent_at)%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @error_message_requests.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#error-messages" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@error_message_requests.size%></span> <%= chevron_right %>Fix these delivery and other errors</a>
      </div>
      <div id="error-messages" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for @request in @error_message_requests %>
              <tr>
                <td class="link">
                  <%= request_both_links(@request) %>
                </td>
                <td class="span2">
                  <%=simple_date(@request.info_request_events.last.created_at)%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @attention_requests.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#attention-messages" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@attention_requests.size%></span><%= chevron_right %> Review requests marked by users as requiring your attention
</a>
      </div>
      <div id="attention-messages" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for @request in @attention_requests %>
              <tr>
                <td class="link">
                  <%= request_both_links(@request) %>
                </td>
                <td class="span2">
                  <%=simple_date(@request.info_request_events.last.created_at)%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @requires_admin_requests.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#requires-admin" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@requires_admin_requests.size%></span><%= chevron_right %> These require administrator attention</a>
      </div>
      <div id="requires-admin" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for @request in @requires_admin_requests %>
              <tr>
                <td class="link">
                  <%= request_both_links(@request) %>
                </td>
                <td class="span2">
                  <%=simple_date(@request.info_request_events.last.created_at)%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @blank_contacts.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#blank-contacts" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@blank_contacts.size%></span><%= chevron_right %> Find missing FOI email for these public authorities (try phoning!)</a>
      </div>
      <div id="blank-contacts" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for @blank_contact in @blank_contacts %>
              <tr>
                <td class="link">
                  <%= public_body_both_links(@blank_contact) %>
                </td>
                <td class="span2">
                  <%=simple_date(@blank_contact.updated_at)%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <% if @old_unclassified.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#unclassified" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%=@old_unclassified.size%></span><%= chevron_right %> Classify responses that are still unclassified <%=InfoRequest::OLD_AGE_IN_DAYS.inspect %> after response</a>
      </div>
      <div id="unclassified" class="accordion-body collapse">
        <table class="table table-striped table-condensed">
          <tbody>
            <% for @request in @old_unclassified %>
                <tr>
                  <td class="link">
                    <%= request_both_links(@request) %>
                  </td>
                  <td class="span2">
                    <%=simple_date(@request.get_last_public_response_event.created_at)%>
                  </td>
                </tr>
            <% end %>
          </tbody>

        </table>
      </div>
    </div>
  <% end %>

  <% if @new_body_requests.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#new-authorities" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%= @new_body_requests.size %></span><%= chevron_right %> Add new authorities</a>
      </div>
      <div id="new-authorities" class="accordion-body collapse">
            <% for @change_request in @new_body_requests %>
              <%= render :partial => 'change_request_summary'%>
              <%= form_tag admin_change_request_update_path(@change_request), :class => "form form-horizontal" do %>
                <%= submit_tag 'Close', :class => "btn btn-danger" %>
                <%= link_to("Close and respond", admin_change_request_edit_path(@change_request), :class => 'btn') %>
                <%= link_to("Add authority", admin_body_new_path(:change_request_id => @change_request.id), :class => 'btn btn-primary') %>
              <% end %>

            <% end %>
      </div>
    </div>
  <% end %>

  <% if @body_update_requests.size > 0 %>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" href="#update-authorities" data-toggle="collapse" data-parent="things-to-do"><span class="label label-important"><%= @body_update_requests.size %></span><%= chevron_right %> Update authorities</a>
      </div>
      <div id="update-authorities" class="accordion-body collapse">
        <% for @change_request in @body_update_requests %>
            <%= render :partial => 'change_request_summary' %>
            <%= form_tag admin_change_request_update_path(@change_request), :class => "form form-horizontal" do %>
              <%= submit_tag 'Close', :class => "btn btn-danger" %>
            <%= link_to("Close and respond", admin_change_request_edit_path(@change_request), :class => 'btn') %>
            <%= link_to("Make update", admin_body_edit_path(@change_request.public_body, :change_request_id => @change_request.id), :class => 'btn btn-primary') %>
            <% end %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if @holding_pen_messages.size == 0 && @old_unclassified.size == 0 && @requires_admin_requests.size == 0 && @blank_contacts.size == 0 && @attention_requests.size == 0 && @new_body_requests.size == 0 && @body_update_requests.size == 0 %>
  <div class="row">
    <div class="span12 alert alert-success">
      No pending administration required.
    </div>
  </div>
<% end %>

app/views/admin_general/timeline.html.erb
<% @title = "Timeline" %>
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to "Hour", admin_timeline_path(:hour => 1), :class => "btn" %>
    <%= link_to "Day", admin_timeline_path(:day => 1), :class => "btn" %>
    <%= link_to "2 days", admin_timeline_path, :class => "btn" %>
    <%= link_to "Week", admin_timeline_path(:week => 1), :class => "btn" %>
    <%= link_to "Month", admin_timeline_path(:month => 1), :class => "btn" %>
    <%= link_to "All time", admin_timeline_path(:all => 1), :class => "btn" %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <h1><%=h @events_title%></h1>
  </div>
</div>

<% last_date = nil %>
<% for event, event_at in @events %>
    <% if last_date != event_at.to_date %>
        <% if last_date.nil? %>
            <p>
        <% end %>
        <h3><%= simple_date(event_at) %></h3>
        <p>
    <% else %>
        <br>
    <% end %>
    <% last_date = event_at.to_date %>

    <%= simple_time(event_at) %>

    <% if event.is_a? InfoRequestEvent %>
        <%= request_both_links(event.info_request) %>
        <% if event.event_type == 'edit' %>
            was edited by administrator <strong><%=h event.params[:editor] %></strong>.
            <% for p in ['title', 'described_state', 'awaiting_description']
                    if event.params[p.to_sym] != event.params[('old_'+p).to_sym]
                        %> Changed <%=p%> from '<%=h event.params[('old_'+p).to_sym]%>' to '<%=h event.params[p.to_sym] %>'. <%
                    end
               end
            %>
        <% elsif event.event_type == 'edit_outgoing' %>
            <% outgoing_message = OutgoingMessage.find(event.params[:outgoing_message_id].to_i) %>
            had outgoing message edited by administrator <strong><%=h event.params[:editor] %></strong>.
            <% if outgoing_message %>
                <% for p in ['body']
                        if event.params[p.to_sym] != event.params[('old_'+p).to_sym]
                            %> Changed <%=p%> from '<%=h event.params[('old_'+p).to_sym]%>' to '<%=h event.params[p.to_sym] %>'. <%
                        end
                   end
                %>
            <% else %>
                Missing outgoing message, internal error.
            <% end %>
        <% elsif event.event_type == 'edit_comment' %>
            <% comment = Comment.find(event.params[:comment_id].to_i) %>
            had annotation edited by administrator <strong><%=h event.params[:editor] %></strong>.
            <% if comment %>
                <% for p in ['body']
                        if event.params[p.to_sym] != event.params[('old_'+p).to_sym]
                            %> Changed <%=p%> from '<%=h event.params[('old_'+p).to_sym]%>' to '<%=h event.params[p.to_sym] %>'. <%
                        end
                   end
                %>
            <% else %>
                Missing annotation, internal error.
            <% end %>
        <% elsif event.event_type == 'destroy_incoming' %>
            had incoming message deleted by administrator <strong><%=h event.params[:editor] %></strong>.
        <% elsif event.event_type == 'destroy_outgoing' %>
            had outgoing message deleted by administrator <strong><%=h event.params[:editor] %></strong>.
        <% elsif event.event_type == 'hide' %>
            was hidden by administrator <strong><%=h event.params[:editor] %></strong>.
        <% elsif event.event_type == 'redeliver_outgoing' %>
            had incoming message redelivered to another request by administrator <strong><%=h event.params[:editor] %></strong>.
         <% elsif event.event_type == 'response' %>
            <% incoming_message = event.incoming_message %>
            received
            <%= link_to 'a response', incoming_message_path(incoming_message) %>
            from <%=h event.info_request.public_body.name %>.
        <% elsif event.event_type == 'sent' %>
            was initially sent to <%=h event.params[:email]%> at <%=h event.info_request.public_body.name %>.
        <% elsif event.event_type == 'resent' %>
            had the request resent to <%=h event.params[:email]%> at <%=h event.info_request.public_body.name %>.
        <% elsif event.event_type == 'followup_sent' %>
            had a follow up message sent to <%=h event.info_request.public_body.name %>.
        <% elsif event.event_type == 'comment' %>
            had an annotation posted by <%=h event.comment.user.name %>.
        <% elsif event.event_type == 'status_update' %>
                had its status updated by <%= event.params[:user_id] ? User.find(event.params[:user_id]).name : event.params[:script] %> from '<%= h event.params[:old_described_state] %>' to '<%= h event.params[:described_state] %>'.
        <% else %>
            had '<%=event.event_type%>' done to it, parameters <%=h event.params_yaml%>.
        <% end %>
    <% else %>
        <%= public_body_both_links(event.public_body) %>
        was created/updated by administrator <strong><%=h event.last_edit_editor %></strong>
    <% end %>
<% end %>
<%= will_paginate(@events, :class => 'paginator') %>
<% if not @events.empty? %>
</p>
<% end %>