config/routes.rb
    match '/search/all' => 'general#search_redirect', :as => :search_redirect
    # `combined` is the search query, and then if sorted a "/newest" at the end.
    # Couldn't find a way to do this in routes which also picked up multiple other slashes
    # and dots and other characters that can appear in search query. So we sort it all
    # out in the controller.
    match '/search/*combined/all' => 'general#search', :as => :search_general, :view => 'all'
    match '/search(/*combined)' => 'general#search', :as => :search_general
    match '/advancedsearch' => 'general#search_redirect', :as => :advanced_search, :advanced => true
    match '/version.:format' => 'general#version', :as => :version
    #####

    ##### Request controller
    match '/list/recent' => 'request#list', :as => :request_list_recent, :view => 'recent'
    match '/list/all' => 'request#list', :as => :request_list_all, :view => 'all'
    match '/list/successful' => 'request#list', :as => :request_list_successful, :view => 'successful'
    match '/list/unsuccessful' => 'request#list', :as => :request_list_unsuccessful, :view => 'unsuccessful'
    match '/list/awaiting' => 'request#list', :as => :request_list_awaiting, :view => 'awaiting'
    match '/list' => 'request#list', :as => :request_list

    match '/select_authority' => 'request#select_authority', :as => :select_authority
    match '/select_authorities' => 'request#select_authorities', :as => :select_authorities

    match '/new' => 'request#new', :as => :new_request
    match '/new/:url_name' => 'request#new', :as => :new_request_to_body
    match '/new_batch' => 'request#new_batch', :as => :new_batch

    match '/request/search_ahead' => 'request#search_typeahead', :as => :search_ahead

    match '/request/:url_title' => 'request#show', :as => :show_request
    match '/request/:url_title/new' => 'request#show', :as => :show_new_request
    match '/details/request/:url_title' => 'request#details', :as => :details_request
    match '/similar/request/:url_title' => 'request#similar', :as => :similar_request

    match '/request/:id/describe' => 'request#describe_state', :as => :describe_state
    match '/request/:url_title/describe/:described_state' => 'request#describe_state_message', :as => :describe_state_message
    match '/request/:id/response' => 'request#show_response', :as => :show_response_no_followup
    match '/request/:id/response/:incoming_message_id' => 'request#show_response', :as => :show_response
    match '/request/:id/response/:incoming_message_id/attach/html/:part/*file_name' => 'request#get_attachment_as_html', :format => false, :as => :get_attachment_as_html
    match '/request/:id/response/:incoming_message_id/attach/:part(/*file_name)' => 'request#get_attachment', :format => false, :as => :get_attachment

    match '/request_event/:info_request_event_id' => 'request#show_request_event', :as => :info_request_event

    match '/upload/request/:url_title' => 'request#upload_response', :as => :upload_response
    match '/request/:url_title/download' => 'request#download_entire_request', :as => :download_entire_request
    ####

    resources :health_checks, :only => [:index]

    resources :request, :only => [] do
        resource :report, :only => [:new, :create]
    end

    resources :info_request_batch, :only => :show

    #### User controller
    # Use /profile for things to do with the currently signed in user.
    # Use /user/XXXX for things that anyone can see about that user.
    # Note that /profile isn't indexed by search (see robots.txt)
    match '/profile/sign_in' => 'user#signin', :as => :signin
    match '/profile/sign_up' => 'user#signup', :as => :signup, :via => :post
    match '/profile/sign_up' => 'user#signin', :via => :get
    match '/profile/sign_out' => 'user#signout', :as => :signout

    match '/c/:email_token' => 'user#confirm', :as => :confirm
    match '/user/:url_name' => 'user#show', :as => :show_user
    match '/user/:url_name/profile' => 'user#show', :as => :show_user_profile, :view => 'profile'
    match '/user/:url_name/requests' => 'user#show', :as => :show_user_requests, :view => 'requests'
    match '/user/:url_name/wall' => 'user#wall', :as => :show_user_wall
    match '/user/contact/:id' => 'user#contact', :as => :contact_user

    match '/profile/change_password' => 'user#signchangepassword', :as => :signchangepassword
    match '/profile/change_email' => 'user#signchangeemail', :as => :signchangeemail

    match '/profile/set_photo' => 'user#set_profile_photo', :as => :set_profile_photo
    match '/profile/clear_photo' => 'user#clear_profile_photo', :as => :clear_profile_photo
    match '/user/:url_name/photo.png' => 'user#get_profile_photo', :as => :get_profile_photo
    match '/profile/draft_photo/:id.png' => 'user#get_draft_profile_photo', :as => :get_draft_profile_photo
    match '/profile/set_about_me' => 'user#set_profile_about_me', :as => :set_profile_about_me
    match '/profile/set_receive_alerts' => 'user#set_receive_email_alerts', :as => :set_receive_email_alerts
    match '/profile/river' => 'user#river', :as => :river
    ####

    #### PublicBody controller
    match '/body/search_ahead' => 'public_body#search_typeahead', :as => :search_ahead_bodies
    match '/body' => 'public_body#list', :as => :list_public_bodies
    match '/body/list/all' => 'public_body#list', :as => :list_public_bodies_default
    match '/body/list/:tag' => 'public_body#list', :as => :list_public_bodies
    match '/local/:tag' => 'public_body#list_redirect', :as => :list_public_bodies_redirect
    match '/body/all-authorities.csv' => 'public_body#list_all_csv', :as => :all_public_bodies_csv
    match '/body/:url_name' => 'public_body#show', :as => :show_public_body, :view => 'all'
    match '/body/:url_name/all' => 'public_body#show', :as => :show_public_body_all, :view => 'all'
    match '/body/:url_name/successful' => 'public_body#show', :as => :show_public_body_successful, :view => 'successful'
    match '/body/:url_name/unsuccessful' => 'public_body#show', :as => :show_public_body_unsuccessful, :view => 'unsuccessful'
    match '/body/:url_name/awaiting' => 'public_body#show', :as => :show_public_body_awaiting, :view => 'awaiting'
    match '/body/:url_name/view_email' => 'public_body#view_email', :as => :view_public_body_email
    match '/body/:url_name/:tag' => 'public_body#show', :as => :show_public_body_tag
    match '/body/:url_name/:tag/:view' => 'public_body#show', :as => :show_public_body_tag_view
    match '/body_statistics' => 'public_body#statistics', :as => :public_bodies_statistics
    ####

    resource :change_request, :only => [:new, :create], :controller => 'public_body_change_requests'

    #### Comment controller
    match '/annotate/request/:url_title' => 'comment#new', :as => :new_comment, :type => 'request'
    ####

    #### Services controller
    match '/country_message' => 'services#other_country_message', :as => :other_country_message
    match '/hidden_user_explanation' => 'services#hidden_user_explanation', :as => :hidden_user_explanation
    ####

    #### Track controller
    # /track/ is for setting up an email alert for the item
    # /feed/ is a direct RSS feed of the item
    match '/:feed/request/:url_title' => 'track#track_request', :as => :track_request, :feed => /(track|feed)/
    match '/:feed/list/:view' => 'track#track_list', :as => :track_list, :view => nil, :feed => /(track|feed)/
    match '/:feed/body/:url_name' => 'track#track_public_body', :as => :track_public_body, :feed => /(track|feed)/
    match '/:feed/user/:url_name' => 'track#track_user', :as => :track_user, :feed => /(track|feed)/
    # TODO: :format doesn't work. See hacky code in the controller that makes up for this.
    match '/:feed/search/:query_array' => 'track#track_search_query',
          :as => :track_search,
          :feed => /(track|feed)/,
          :constraints => { :query_array => /.*/ }

    match '/track/update/:track_id' => 'track#update', :as => :update
    match '/track/delete_all_type' => 'track#delete_all_type', :as => :delete_all_type
    match '/track/feed/:track_id' => 'track#atom_feed', :as => :atom_feed
    ####

    #### Help controller
    match '/help/unhappy/:url_title' => 'help#unhappy', :as => :help_unhappy
    match '/help/about' => 'help#about', :as => :help_about
    match '/help/alaveteli' => 'help#alaveteli', :as => :help_alaveteli
    match '/help/contact' => 'help#contact', :as => :help_contact
    match '/help/officers' => 'help#officers', :as => :help_officers
    match '/help/requesting' => 'help#requesting', :as => :help_requesting
    match '/help/privacy' => 'help#privacy', :as => :help_privacy
    match '/help/api' => 'help#api', :as => :help_api
    match '/help/credits' => 'help#credits', :as => :help_credits
    match '/help/:action' => 'help#action', :as => :help_general
    match '/help' => 'help#index'
    ####

    #### Holiday controller
    match '/due_date/:holiday' => 'holiday#due_date', :as => :due_date
    ####

    #### RequestGame controller
    match '/categorise/play' => 'request_game#play', :as => :categorise_play
    match '/categorise/request/:url_title' => 'request_game#show', :as => :categorise_request
    match '/categorise/stop' => 'request_game#stop', :as => :categorise_stop
    ####

    #### AdminPublicBody controller
    match '/admin/missing_scheme' => 'admin_public_body#missing_scheme', :as => :admin_body_missing
    match '/admin/body' => 'admin_public_body#index', :as => :admin_body_index
    match '/admin/body/list' => 'admin_public_body#list', :as => :admin_body_list
    match '/admin/body/show/:id' => 'admin_public_body#show', :as => :admin_body_show
    match '/admin/body/new' => 'admin_public_body#new', :as => :admin_body_new
    match '/admin/body/edit/:id' => 'admin_public_body#edit', :as => :admin_body_edit
    match '/admin/body/update/:id' => 'admin_public_body#update', :as => :admin_body_update

app/views/user/_signin.html.erb
<div id="signin">

<%= form_tag({:action => "signin"}, {:id => "signin_form"}) do %>
    <%= foi_error_messages_for :user_signin %>

    <!--<% if not sign_in_as_existing_user %>
    <h2><%= _('If you\'ve used {{site_name}} before', :site_name=>site_name)%></h2>
    <% end %>-->

    <p>
    <label class="form_label" for="user_signin_email"><%= _('Your e-mail:')%></label>
    <%= text_field 'user_signin', 'email', { :size => 20, :tabindex => 10 } %>
    </p>

    <p>
    <label class="form_label" for="user_signin_password"><%= _('Password:')%></label>
    <%= password_field 'user_signin', 'password', { :size => 15, :tabindex => 20 } %>
    </p>

    <p class="form_note">
    <%= link_to _('Forgotten your password?'), signchangepassword_path + "?pretoken=" + h(params[:token]), :tabindex => 30 %>
    </p>

    <p class="form_checkbox">
    <%= check_box_tag 'remember_me', "1", false, :tabindex => 40 %>
    <label for="remember_me"><%= _('Remember me</label> (keeps you signed in longer;
    do not use on a public computer) ')%></p>

    <div class="form_button">
    <%= hidden_field_tag 'token', params[:token], {:id => 'signin_token' } %>
    <%= hidden_field_tag :modal, params[:modal], {:id => 'signin_modal' } %>
    <%= submit_tag _('Sign in'), :tabindex => 50 %>
    </div>
<% end %>

</div>

app/views/user/_user_listing_single.html.erb
<% if @highlight_words.nil? 
      @highlight_words = []
end %>

<div class="user_listing">
    <% if display_user.profile_photo %>
        <div class="user_photo_on_search">
            <a href="<%=user_path(display_user)%>">
            <img src="<%= get_profile_photo_url(:url_name => display_user.url_name) %>" alt="">
            </a>
        </div>
    <% end %>

    <span class="head <% if display_user.profile_photo %>no_icon<% end %>">
        <%= link_to highlight_words(display_user.name, @highlight_words), user_path(display_user) %>
    </span>

    <span class="bottomline">
        <%= pluralize(display_user.info_requests.size, "request") %> <%= _('made.')%>
        <%= pluralize(display_user.visible_comments.size, "annotation") %> <%= _('made.')%>
        <%= _('Joined in')%> <%= display_user.created_at.year %>.
    </span>

</div>

app/views/user/banned.html.erb
<% @title = "Banned from this site" %>

<h1><%=@title%></h1>

<p>
<%=@details%>
</p>

<p><%= _('You will be unable to make new requests, send follow ups, add annotations or
send messages to other users. You may continue to view other requests, and set
up
email alerts.')%></p>

<p>
<%= _('If you would like us to lift this ban, then you may politely
<a href="/help/contact">contact us</a> giving reasons.
')%></p>

app/views/user/confirm.html.erb
<% @title = _("Now check your email!") %>

<h1 class="confirmation_heading"><%= _("Now check your email!") %></h1>

<p class="confirmation_message">
<%= _('We\'ve sent you an email, and you\'ll need to click the link in it before you can
continue.') %>
</p>

<p class="confirmation_message">
<%= _('<small>If you use web-based email or have "junk mail" filters, also check your
bulk/spam mail folders. Sometimes, our messages are marked that way.</small>
</p>') %>

app/views/user/contact.html.erb
<% @title = "Contact " + h(@recipient_user.name) %>

<% if not @user %>
    <% raise "You need to be logged in" %>
<% end %>

<%= foi_error_messages_for :contact %>

<%= form_for :contact do |f| %>

    <div class="form_note">
      <h1><%= _("Contact {{recipient}}", :recipient => h(@recipient_user.name)) %></h1>
    </div>

    <p>
        <label class="form_label"><%= _("From") %>:</label>
        <%= h(@user.name_and_email) %>
    </p>

    <p>
        <label class="form_label" for="contact_subject"><%= _("Subject") %>:</label>
        <%= f.text_field :subject, :size => 50 %>
    </p>

    <p>
      <label class="form_label" for="contact_message"><%= _("Message") %>:</label>
        <%= f.text_area :message, :rows => 10, :cols => 50 %>
    </p>

    <p class="form_note">
        <% if @user == @recipient_user %>
            <%= _('<strong>Note:</strong> You\'re sending a message to yourself, presumably
            to try out how it works.')%>
        <% else %>
           <%= _(' <strong>Privacy note:</strong> Your email address will be given to')%>
            <%= user_link(@recipient_user) %><%= _(' when you send this message.')%>
        <% end %>
    </p>

    <div class="form_button">
        <%= hidden_field_tag(:submitted_contact_form, { :value => 1 } ) %>
        <%= submit_tag _("Send message") %>
    </div>

<% end %>

app/views/user/no_cookies.html.erb
<% @title = "Cookies not enabled" %>

<h1><%= _('Please enable "cookies" to carry on')%></h1>

<p><%= _('To carry on, you need to sign in or make an account. Unfortunately, there
was a technical problem trying to do this.')%></p>

<p><%= _('It may be that your browser is not set to accept a thing called "cookies",
or cannot do so.  If you can, please enable cookies, or try using a different
browser.  Then press refresh to have another go.')%></p>

<p><%= _('If your browser is set to accept cookies and you are seeing this message,
then there is probably a fault with our server.')%> 

<%= _('Please <a href="{{url}}">get in touch</a> with us so we can fix it.', :url => help_contact_path.html_safe) %>

 <%= _('Let us know what you were doing when this message
appeared and your browser and operating system type and version.')%></p>

<p><%= _('If you are still having trouble, please <a href="{{url}}">contact us</a>.', :url => help_contact_path.html_safe) %>
</p>

app/views/user/show.html.erb
<% if @show_requests %>
  <% @title =  _("{{user_name}} - Freedom of Information requests", :user_name => h(@display_user.name)) %>
<% else %>
  <% @title = _("{{user_name}} - user profile", :user_name => h(@display_user.name)) %>
<% end %>

<% if (@same_name_users.size >= 1) %>
    <p><%= _('There is <strong>more than one person</strong> who uses this site and has this name.
    One of them is shown below, you may mean a different one:')%> <% for @same_name_user in @same_name_users %>
        <%= user_link(@same_name_user) %>
    <% end %>
<% end%>

<% if @show_profile && @is_you && @undescribed_requests.size > 0 %>
    <div class="undescribed_requests">
        <p><%= _('Please <strong>go to the following requests</strong>, and let us
        know if there was information in the recent responses to them.')%></p>
        <ul>
        <% for undescribed_request in @undescribed_requests %>
            <li><%=request_link(undescribed_request)%></li>
        <% end %>
        </ul>
        <p>
      <%= _('Thanks very much - this will help others find useful stuff. We\'ll
            also, if you need it, give advice on what to do next about your
            requests.')%>
        </p>
    </div>
<% end %>

<% if @show_profile %>
<div id="user_profile_header">
  <div id="header_right">
     <% if !@track_thing.nil? %>
       <h2><%= _('Track this person')%></h2>
       <%= render :partial => 'track/tracking_links', :locals => { :track_thing => @track_thing, :own_request => false, :location => 'sidebar' } %>
     <% end %>
     <% if !@xapian_requests.nil? %>
       <h2><%= _('On this page')%></h2>
       <a href="#foi_requests"><%= _('FOI requests')%></a>
       <br><a href="#annotations"><%= _('Annotations')%></a>
     <% end %>
  </div>

  <div id="header_left">
    <p id="user_photo_on_profile">
        <% if @display_user.profile_photo %>
            <% if @is_you %>
            <a href="<%= set_profile_photo_url() %>">
            <% end %>
                <img src="<%= get_profile_photo_url(:url_name => @display_user.url_name) %>" alt="">
            <% if @is_you %>
            </a>
            <% end %>
        <% else %>
            <% if @is_you %>
                <span id="set_photo">
                    <%= link_to _('Set your profile photo'), set_profile_photo_path %>
                </span>
            <% end %>
        <% end %>
    </p>

    <h1> <%= h(@display_user.name) + (@is_you ? _(" (you)") : "") %></h1>

    <p class="subtitle">
       <%= _('Joined {{site_name}} in', :site_name=>site_name) %> <%= @display_user.created_at.year %>
        <% if !@user.nil? && @user.admin_page_links? %>
        (<%= link_to "admin", admin_user_show_path(@display_user) %>)
        <% end %>
    </p>

    <p>
        <%= link_to _('Send message to ') + h(@display_user.name), contact_user_path(:id => @display_user.id) %>
        <% if @is_you %>
            (<%= _('just to see how it works')%>)
        <% end %>
    </p>

    <% if @display_user.public_banned? %>
        <div id="user_public_banned">
            <p>
                <strong>
                  <%= _('This user has been banned from {{site_name}} ', :site_name=>site_name)%>
                </strong>
            </p>
            <p>
               <%= _('They have been given the following explanation:')%>
            </p>
            <p class="details">
                <%= @display_user.can_fail_html %>
            </p>
        </div>
    <% end %>

    <%= render :partial => 'user/show_user_info' %>

    <% if not @is_you %>
        <p id="user_not_logged_in">
           <%= _('<a href="{{url}}">Sign in</a> to change password, subscriptions and more ({{user_name}} only)',:user_name=>h(@display_user.name), :url => signin_url(:r => request.fullpath).html_safe) %>
        </p>
    <% end %>
  </div>
</div>
<div style="clear:both"></div>
<% end %>

<% if @show_batches %>

  <% if @is_you && !@display_user.info_request_batches.empty? %>
      <h2 class="batch_results" id="batch_requests">
          <%=  n_('Your {{count}} batch requests', 'Your {{count}} batch requests', @display_user.info_request_batches.size, :count => @display_user.info_request_batches.size) %>
      </h2>
      <%= render :partial => 'info_request_batch/info_request_batch', :collection => @display_user.info_request_batches %>
    <% end %>

<% end %>

<% if @show_requests %>
<div id="user_profile_search">
    <%= form_tag(show_user_url, :method => "get", :id=>"search_form") do %>
    <div>
        <%= text_field_tag(:user_query, params[:user_query], {:title => "type your search term here" }) %>
        <%= select_tag :request_latest_status,
                       options_from_collection_for_select(@request_states, 'value', 'text', params[:request_latest_status]),
                       :prompt => _('Filter by Request Status (optional)') %>
        <% if @is_you %>
            <%= submit_tag(_("Search your contributions")) %>
        <% else %>
            <%= submit_tag(_("Search contributions by this person")) %>
        <% end %>
    </div>
    <% end %>

    <% if !@xapian_requests.nil? %>
        <% if @xapian_requests.results.empty? %>
            <% if @page == 1 %>
                <h2 class="foi_results" id="foi_requests"><%= @is_you ? _('Freedom of Information requests made by you') : _('Freedom of Information requests made by this person') %> <%= @match_phrase %>
</h2>
                <p><%= @is_you ? _('You have made no Freedom of Information requests using this site.') : _('This person has made no Freedom of Information requests using this site.') %>
                <%= @page_desc %>
            <% end %>
        <% else %>
            <h2 class="foi_results" id="foi_requests">
                <%= @is_you ? n_('Your {{count}} Freedom of Information request', 'Your {{count}} Freedom of Information requests', @xapian_requests.matches_estimated, :count => @xapian_requests.matches_estimated) : n_("This person's {{count}} Freedom of Information request", "This person's {{count}} Freedom of Information requests",  @xapian_requests.matches_estimated, :count => @xapian_requests.matches_estimated) %>
                <!-- matches_estimated <%=@xapian_requests.matches_estimated%> -->
                <%= @match_phrase %>
                <%= @page_desc %>
            </h2>


            <% for result in @xapian_requests.results %>
                <%= render :partial => 'request/request_listing_via_event', :locals => { :event => result[:model] } %>
            <% end %>

            <%= will_paginate WillPaginate::Collection.new(@page, @per_page, @display_user.info_requests.size) %>
        <% end %>
    <% else %>
      <% if @show_requests %>
        <h2 class="foi_results" id="foi_requests"><%= @is_you ? _('Freedom of Information requests made by you') : _('Freedom of Information requests made by this person') %> </h2>
        <p><%= _('The search index is currently offline, so we can\'t show the Freedom of Information requests this person has made.')%></p>
      <% end %>
    <% end %>

    <% if !@xapian_comments.nil? %>
        <% if @xapian_comments.results.empty? %>
            <% if @page == 1 %>
                <h2><%= @is_you ? _('Your annotations') : _('This person\'s annotations') %>
                    <%= @match_phrase %>
                </h2>
                <p><%= _('None made.')%></p>
            <% end %>
        <% else %>
            <h2 id="annotations">
                <%= @is_you ? n_('Your {{count}} annotation', 'Your {{count}} annotations', @display_user.visible_comments.size, :count => @display_user.visible_comments.size) : n_("This person's {{count}} annotation", "This person's {{count}} annotations", @display_user.visible_comments.size, :count => @display_user.visible_comments.size) %>
                  <!-- matches_estimated <%=@xapian_comments.matches_estimated%> -->
                <%= @page_desc %>
            </h2>

            <% for result in @xapian_comments.results %>
                <%= render :partial => 'request/request_listing_via_event', :locals => { :event => result[:model] } %>
            <% end %>

            <%= will_paginate WillPaginate::Collection.new(@page, @per_page, @display_user.visible_comments.size) %>
        <% end %>
    <% end %>

</div>
<% end %>
<% if @show_profile && @is_you %>
    <h2 id="email_subscriptions"> <%= _("Things you're following")%></h2>
    <%= render :partial => 'change_receive_email' %>
    <br>
    <% if @track_things.empty? %>
        <p><%= _("You're not following anything.")%></p>
    <% else %>
        <% if @track_things_grouped.size == 1 %>
            <%= form_tag({:controller => 'track', :action => 'delete_all_type'}, :class => "feed_form") do %>
                <h3>
                    <%=TrackThing.track_type_description(@track_things[0].track_type)%>
                    <%= hidden_field_tag 'track_type', @track_things[0].track_type %>
                    <%= hidden_field_tag 'user', @display_user.id %>
                    <%= hidden_field_tag 'r', request.fullpath %>
                    <% if @track_things.size > 1 %>
                        <%= submit_tag _('unsubscribe all') %>
                    <% end %>
                </h3>
            <% end %>
        <% end %>
        <% for track_type, track_things in @track_things_grouped %>
            <% if @track_things_grouped.size > 1 %>
                <%= form_tag({:controller => 'track', :action => 'delete_all_type'}, :class => "feed_form") do %>
                    <h3>
                        <%=TrackThing.track_type_description(track_type)%>
                        <%= hidden_field_tag 'track_type', track_type %>
                        <%= hidden_field_tag 'user', @display_user.id %>
                        <%= hidden_field_tag 'r', request.fullpath %>
                        <% if track_things.size > 1 %>
                            <%= submit_tag _('unsubscribe all')%>
                        <% end %>
                    </h3>
                <% end %>
            <% end %>

            <ul>
            <% for track_thing in track_things %>
                <li>
                    <%= form_tag({:controller => 'track', :action => 'update', :track_id => track_thing.id}, :class => "feed_form") do %>
                        <div>
                            <%= track_description(track_thing) %>
                            <%= hidden_field_tag 'track_medium', "delete", { :id => 'track_medium_' + track_thing.id.to_s } %>
                            <%= hidden_field_tag 'r', request.fullpath, { :id => 'r_' + track_thing.id.to_s }  %>
                            <%= submit_tag _('unsubscribe') %>
                        </div>
                    <% end %>
                </li>
            <% end %>
            </ul>
        <% end %>
    <% end %>
<% end %>

app/views/user/sign.html.erb
<% if !@post_redirect.nil? && @post_redirect.reason_params[:user_name] %>
    <% @title = _("Sign in") %>
    <div id="sign_alone">

        <p id="sign_in_reason">
        <% if @post_redirect.reason_params[:web].empty? %>
            <%= _('Please sign in as ')%><%= link_to h(@post_redirect.reason_params[:user_name]), @post_redirect.reason_params[:user_url] %>.
        <% else %>
            <%= @post_redirect.reason_params[:web] %>,
             <%= _('please sign in as ')%><%= link_to h(@post_redirect.reason_params[:user_name]), @post_redirect.reason_params[:user_url] %>.
        <% end %>
  </p>
        <% if @post_redirect.post_params["controller"] == "admin_general" %>
          <% unless AlaveteliConfiguration::disable_emergency_user %>
           <p id="superuser_message"><%= _("Don't have a superuser account yet?") %> <%= link_to _("Sign in as the emergency user"), @post_redirect.uri + "?emergency=1" %></p>
          <% end %>
        <% end %>

    <%= render :partial => 'signin', :locals => { :sign_in_as_existing_user => true } %>

    </div>

<% else %>
    <% @title = _('Sign in or make a new account') %>

    <div id="sign_together">
      <% if !@post_redirect.nil? %>
        <p id="sign_in_reason">
          <% if @post_redirect.reason_params[:web].empty? %>
            <%= _('Please sign in or make a new account.') %>
          <% else %>
            <%= _('{{reason}}, please sign in or make a new account.', :reason => @post_redirect.reason_params[:web]) %>
          <% end %>
        </p>
      <% end %>
        <div id="left_half">
          <h1><%= _('Sign in') %></h1>
          <%= render :partial => 'signin', :locals => { :sign_in_as_existing_user => false } %>
        </div>
        <div id="middle_strip">
        <%= _('- or -') %>
        </div>
        <div id="right_half">
          <h1><%= _('Sign up') %></h1>
          <%= render :partial => 'signup' %>
        </div>
        <div style="clear:both"></div>
    </div>

<% end %>

app/views/user/wall.html.erb
<% @title = h(@display_user.name) + _(" - wall") %>
<div class="medium_column">
 <% if @is_you %>
  <h2><%= _("My wall") %></h2>
  <p><%= _('You can change the requests and users you are following on <a href="{{profile_url}}">your profile page</a>.', :profile_url => show_user_profile_path) %></p>
  <%= render :partial => 'change_receive_email' %>
 <% else %>
  <h2><%= _("This is <a href=\"{{profile_url}}\">{{user_name}}'s</a> wall", :profile_url => show_user_profile_path, :user_name => h(@display_user.name)) %></h2>
 <% end %>
</div>
<div id="user_profile_search">
 <% if !@feed_results.nil? and !@feed_results.empty? %>
  <% for result in @feed_results %>
   <%= render :partial => 'request/wall_listing', :locals => { :event => result, :info_request => result.info_request } %>
  <% end %>
 <% else %>
  <p><%= _("There is nothing to display yet.") %></p>
 <% end %>
</div>