config/routes.rb
    match '/body/:url_name/unsuccessful' => 'public_body#show', :as => :show_public_body_unsuccessful, :view => 'unsuccessful'
    match '/body/:url_name/awaiting' => 'public_body#show', :as => :show_public_body_awaiting, :view => 'awaiting'
    match '/body/:url_name/view_email' => 'public_body#view_email', :as => :view_public_body_email
    match '/body/:url_name/:tag' => 'public_body#show', :as => :show_public_body_tag
    match '/body/:url_name/:tag/:view' => 'public_body#show', :as => :show_public_body_tag_view
    match '/body_statistics' => 'public_body#statistics', :as => :public_bodies_statistics
    ####

    resource :change_request, :only => [:new, :create], :controller => 'public_body_change_requests'

    #### Comment controller
    match '/annotate/request/:url_title' => 'comment#new', :as => :new_comment, :type => 'request'
    ####

    #### Services controller
    match '/country_message' => 'services#other_country_message', :as => :other_country_message
    match '/hidden_user_explanation' => 'services#hidden_user_explanation', :as => :hidden_user_explanation
    ####

    #### Track controller
    # /track/ is for setting up an email alert for the item
    # /feed/ is a direct RSS feed of the item
    match '/:feed/request/:url_title' => 'track#track_request', :as => :track_request, :feed => /(track|feed)/
    match '/:feed/list/:view' => 'track#track_list', :as => :track_list, :view => nil, :feed => /(track|feed)/
    match '/:feed/body/:url_name' => 'track#track_public_body', :as => :track_public_body, :feed => /(track|feed)/
    match '/:feed/user/:url_name' => 'track#track_user', :as => :track_user, :feed => /(track|feed)/
    # TODO: :format doesn't work. See hacky code in the controller that makes up for this.
    match '/:feed/search/:query_array' => 'track#track_search_query',
          :as => :track_search,
          :feed => /(track|feed)/,
          :constraints => { :query_array => /.*/ }

    match '/track/update/:track_id' => 'track#update', :as => :update
    match '/track/delete_all_type' => 'track#delete_all_type', :as => :delete_all_type
    match '/track/feed/:track_id' => 'track#atom_feed', :as => :atom_feed
    ####

    #### Help controller
    match '/help/unhappy/:url_title' => 'help#unhappy', :as => :help_unhappy
    match '/help/about' => 'help#about', :as => :help_about
    match '/help/alaveteli' => 'help#alaveteli', :as => :help_alaveteli
    match '/help/contact' => 'help#contact', :as => :help_contact
    match '/help/officers' => 'help#officers', :as => :help_officers
    match '/help/requesting' => 'help#requesting', :as => :help_requesting
    match '/help/privacy' => 'help#privacy', :as => :help_privacy
    match '/help/api' => 'help#api', :as => :help_api
    match '/help/credits' => 'help#credits', :as => :help_credits
    match '/help/:action' => 'help#action', :as => :help_general
    match '/help' => 'help#index'
    ####

    #### Holiday controller
    match '/due_date/:holiday' => 'holiday#due_date', :as => :due_date
    ####

    #### RequestGame controller
    match '/categorise/play' => 'request_game#play', :as => :categorise_play
    match '/categorise/request/:url_title' => 'request_game#show', :as => :categorise_request
    match '/categorise/stop' => 'request_game#stop', :as => :categorise_stop
    ####

    #### AdminPublicBody controller
    match '/admin/missing_scheme' => 'admin_public_body#missing_scheme', :as => :admin_body_missing
    match '/admin/body' => 'admin_public_body#index', :as => :admin_body_index
    match '/admin/body/list' => 'admin_public_body#list', :as => :admin_body_list
    match '/admin/body/show/:id' => 'admin_public_body#show', :as => :admin_body_show
    match '/admin/body/new' => 'admin_public_body#new', :as => :admin_body_new
    match '/admin/body/edit/:id' => 'admin_public_body#edit', :as => :admin_body_edit
    match '/admin/body/update/:id' => 'admin_public_body#update', :as => :admin_body_update
    match '/admin/body/create' => 'admin_public_body#create', :as => :admin_body_create
    match '/admin/body/destroy/:id' => 'admin_public_body#destroy', :as => :admin_body_destroy
    match '/admin/body/import_csv' => 'admin_public_body#import_csv', :as => :admin_body_import_csv
    match '/admin/body/mass_tag_add' => 'admin_public_body#mass_tag_add', :as => :admin_body_mass_tag_add
    ####

    #### AdminPublicBodyCategory controller
    scope '/admin', :as => 'admin' do
        resources :categories,
                  :controller => 'admin_public_body_categories'
    end
    ####

    #### AdminPublicBodyHeading controller
    scope '/admin', :as => 'admin'  do
        resources :headings,
                  :controller => 'admin_public_body_headings',
                  :except => [:index] do
                      post 'reorder', :on => :collection
                      post 'reorder_categories', :on => :member
        end
    end
    ####

    #### AdminPublicBodyChangeRequest controller
    match '/admin/change_request/edit/:id' => 'admin_public_body_change_requests#edit', :as => :admin_change_request_edit
    match '/admin/change_request/update/:id' => 'admin_public_body_change_requests#update', :as => :admin_change_request_update
    ####

    #### AdminGeneral controller
    match '/admin' => 'admin_general#index', :as => :admin_general_index
    match '/admin/timeline' => 'admin_general#timeline', :as => :admin_timeline
    match '/admin/debug' => 'admin_general#debug', :as => :admin_debug
    match '/admin/stats' => 'admin_general#stats', :as => :admin_stats
    ####

    #### AdminRequest controller
    match '/admin/request' => 'admin_request#index', :as => :admin_request_index
    match '/admin/request/list' => 'admin_request#list', :as => :admin_request_list
    match '/admin/request/show/:id' => 'admin_request#show', :as => :admin_request_show
    match '/admin/request/resend' => 'admin_request#resend', :as => :admin_request_resend
    match '/admin/request/edit/:id' => 'admin_request#edit', :as => :admin_request_edit
    match '/admin/request/update/:id' => 'admin_request#update', :as => :admin_request_update
    match '/admin/request/destroy/:id' => 'admin_request#fully_destroy', :as => :admin_request_destroy
    match '/admin/request/edit_comment/:id' => 'admin_request#edit_comment', :as => :admin_request_edit_comment
    match '/admin/request/update_comment/:id' => 'admin_request#update_comment', :as => :admin_request_update_comment
    match '/admin/request/move_request' => 'admin_request#move_request', :as => :admin_request_move_request
    match '/admin/request/generate_upload_url/:id' => 'admin_request#generate_upload_url', :as => :admin_request_generate_upload_url
    match '/admin/request/show_raw_email/:id' => 'admin_request#show_raw_email', :as => :admin_request_show_raw_email
    match '/admin/request/download_raw_email/:id' => 'admin_request#download_raw_email', :as => :admin_request_download_raw_email
    match '/admin/request/mark_event_as_clarification' => 'admin_request#mark_event_as_clarification', :as => :admin_request_clarification
    match '/admin/request/hide/:id' => 'admin_request#hide_request', :as => :admin_request_hide
    ####

    #### AdminIncomingMessage controller
    match '/admin/incoming/destroy' => 'admin_incoming_message#destroy', :as => :admin_incoming_destroy
    match '/admin/incoming/redeliver' => 'admin_incoming_message#redeliver', :as => :admin_incoming_redeliver
    match '/admin/incoming/edit/:id' => 'admin_incoming_message#edit', :as => :admin_incoming_edit
    match '/admin/incoming/update/:id' => 'admin_incoming_message#update', :as => :admin_incoming_update
    ####

    #### AdminOutgoingMessage controller
    match '/admin/outgoing/edit/:id' => 'admin_outgoing_message#edit', :as => :admin_outgoing_edit
    match '/admin/outgoing/destroy/:id' => 'admin_outgoing_message#destroy', :as => :admin_outgoing_destroy
    match '/admin/outgoing/update/:id' => 'admin_outgoing_message#update', :as => :admin_outgoing_update
    ####

    #### AdminUser controller
    match '/admin/user' => 'admin_user#index', :as => :admin_user_index
    match '/admin/user/list' => 'admin_user#list', :as => :admin_user_list
    match '/admin/user/banned' => 'admin_user#list_banned', :as => :admin_user_list_banned
    match '/admin/user/show/:id' => 'admin_user#show', :as => :admin_user_show
    match '/admin/user/edit/:id' => 'admin_user#edit', :as => :admin_user_edit
    match '/admin/user/show_bounce_message/:id' => 'admin_user#show_bounce_message', :as => :admin_user_show_bounce
    match '/admin/user/update/:id' => 'admin_user#update', :as => :admin_user_update
    match '/admin/user/clear_bounce/:id' => 'admin_user#clear_bounce', :as => :admin_user_clear_bounce
    match '/admin/user/destroy_track' => 'admin_user#destroy_track', :as => :admin_user_destroy_track
    match '/admin/user/login_as/:id' => 'admin_user#login_as', :as => :admin_user_login_as
    match '/admin/user/clear_profile_photo/:id' => 'admin_user#clear_profile_photo', :as => :admin_clear_profile_photo
    match '/admin/user/modify_comment_visibility/:id' => 'admin_user#modify_comment_visibility', :as => 'admin_user_modify_comment_visibility'
    ####

    #### AdminTrack controller
    match '/admin/track/list' => 'admin_track#list', :as => :admin_track_list
    ####

    #### AdminCensorRule controller
    match '/admin/censor/new' => 'admin_censor_rule#new', :as => :admin_rule_new
    match '/admin/censor/create' => 'admin_censor_rule#create', :as => :admin_rule_create
    match '/admin/censor/edit/:id' => 'admin_censor_rule#edit', :as => :admin_rule_edit
    match '/admin/censor/update/:id' => 'admin_censor_rule#update', :as => :admin_rule_update
    match '/admin/censor/destroy/:censor_rule_id' => 'admin_censor_rule#destroy', :as => :admin_rule_destroy

    scope '/admin', :as => 'admin' do
        resources :info_requests, :only => [] do
            resources :censor_rules,

app/views/admin_public_body/_form.html.erb
<%= error_messages_for 'public_body' %>

<!--[form:public_body]-->

<div id="div-locales">
  <ul class="locales nav nav-tabs">
  <% I18n.available_locales.each_with_index do |locale, i| %>
    <li><a href="#div-locale-<%=locale.to_s%>" data-toggle="tab" ><%=locale_name(locale.to_s) || _("Default locale")%></a></li>
  <% end %>
  </ul>
  <div class="tab-content">
<%
    for locale in I18n.available_locales do
        if locale==I18n.default_locale  # The default locale is submitted as part of the bigger object...
            prefix = 'public_body'
            object = @public_body
        else                            # ...but additional locales go "on the side"
            prefix = "public_body[translated_versions][]"
            object = @public_body.new_record? ?
                        PublicBody::Translation.new :
                        @public_body.find_translation_by_locale(locale.to_s) || PublicBody::Translation.new
        end
%>
    <%= fields_for prefix, object do |t| %>
    <div class="tab-pane" id="div-locale-<%=locale.to_s%>">
      <div class="control-group">
        <%= t.hidden_field :locale, :value => locale.to_s %>
        <label for="<%= form_tag_id(t.object_name, :name, locale) %>" class="control-label">Name</label>
        <div class="controls">
          <%= t.text_field :name, :id => form_tag_id(t.object_name, :name, locale), :class => "span4" %>
        </div>
      </div>
      <div class="control-group">
        <label for="<%= form_tag_id(t.object_name, :short_name, locale) %>", class="control-label"><%=_("Short name")%></label>
        <div class="controls">
          <%= t.text_field :short_name, :id => form_tag_id(t.object_name, :short_name, locale), :class => "span2"  %>
          <p class="help-block"><%=_("Only put in abbreviations which are really used, otherwise leave blank. Short or long name is used in the URL – don't worry about breaking URLs through renaming, as the history is used to redirect")%></p>
        </div>
      </div>
      <div class="control-group">
        <label for="<%= form_tag_id(t.object_name, :request_email, locale) %>" class="control-label"><%=_("Request email")%></label>
        <div class="controls">
          <%= t.text_field :request_email, :id => form_tag_id(t.object_name, :request_email, locale), :class => "span3" %>
          <p class="help-block"><%=_("set to <strong>blank</strong> (empty string) if can't find an address; these emails are <strong>public</strong> as anyone can view with a CAPTCHA")%></p>
        </div>
      </div>
      <div class="control-group">
        <label for="<%= form_tag_id(t.object_name, :publication_scheme, locale) %>" class="control-label"><%=_("Publication scheme URL")%></label>
        <div class="controls">
          <%= t.text_field :publication_scheme, :size => 60, :id => form_tag_id(t.object_name, :publication_scheme, locale), :class => "span3" %>
        </div>
      </div>
      <div class="control-group">
        <label for="<%= form_tag_id(t.object_name, :notes, locale) %>" class="control-label"><%=_("Public notes")%></label>
        <div class="controls">
          <%= t.text_area :notes, :rows => 3, :id => form_tag_id(t.object_name, :notes, locale), :class => "span6" %>
          <p class="help-block">
            HTML, for users to consider when making FOI requests to the authority
          </p>
        </div>
      </div>
    </div>
<%
        end
    end
%>
  </div>
</div>

<h3>Common Fields</h3>
<div class="control-group">
  <label for="public_body_tag_string" class="control-label"><%=_("Tags")%></label>
  <div class="controls">
    <%= f.text_field :tag_string, :class => "span4" %>
    <p class="help-block">space separated; see list of tags on the right; also <strong>not_apply</strong> if FOI and EIR no longer apply to authority, <strong>eir_only</strong> if EIR but not FOI applies to authority, <strong>defunct</strong> if the authority no longer exists; charity:NUMBER if a registered charity</p>
  </div>
</div>
<div class="control-group">
  <label for="public_body_home_page" class="control-label"><%=_("Home page")%></label>
  <div class="controls">
    <%= f.text_field :home_page, :class => "span4"  %>
    <p class="help-block">(of whole authority, not just their FOI page; set to <strong>blank</strong> (empty string) to guess it from the email)</p>
  </div>
</div>
<div class="control-group">
  <label for="public_body_disclosure_log" class="control-label"><%=_("Disclosure log URL")%></label>
  <div class="controls">
    <%= f.text_field :disclosure_log, :size => 60, :class => "span4" %>
  </div>
</div>
<div class="control-group">
  <label for="public_body_last_edit_comment" class="control-label"><strong>Comment</strong> for this edit</label>
  <div class="controls">
    <%= f.text_area :last_edit_comment, :rows => 3, :class => "span6"  %></p>
    <p class="help-block">put URL or other source of new info</p>
  </div>
</div>
<% if @change_request %>
  <%= render :partial => 'admin_public_body_change_requests/response' %>

<% end %>
<!--[eoform:public_body]-->

app/views/admin_public_body/_one_list.html.erb
<div class="accordion" id="bodies">
  <% for public_body in bodies %>
    <div class="accordion-group">
      <div class="accordion-heading accordion-toggle row">
        <span class="item-title span6">
          <a href="#body_<%=public_body.id%>" data-toggle="collapse" data-parent="requests"><%= chevron_right %></a>
          <%= link_to(public_body.name, admin_body_show_path(public_body), :title => "view full details")%>
        </span>
        <span class="item-metadata span6">
          <%= render :partial => 'tags', :locals => { :body => public_body} %>
        </span>
      </div>
      <div id="body_<%=public_body.id%>" class="item-detail accordion-body collapse row">
        <% public_body.for_admin_column do |name, value, type| %>
          <div>
            <span class="span6">
              <b><%=name%></b>
            </span>
            <span class="span6">
              <% if type == 'datetime' %>
                <%= I18n.l(value, :format => "%e %B %Y %H:%M:%S") %>
                (<%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(value)) %>)
              <% else %>
                <%= h value %>&nbsp;
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= form_tag(admin_body_mass_tag_add_url, :method => "post", :class => "form form-inline" ) do %>
    <p>
       <%= text_field_tag 'new_tag', params[:new_tag], { :size => 15, :id => "mass_add_tag_new_tag_" + table_name } %>
       <%= hidden_field_tag(:query, params[:query], { :id => "mass_add_tag_query_" + table_name } ) %>
       <%= hidden_field_tag(:page, params[:page], { :id => "mass_add_page_" + table_name } ) %>
       <%= hidden_field_tag(:table_name, table_name, { :id => "mass_add_tag_table_name_" + table_name } ) %>
       <%= submit_tag "Add tag to all", :class => "btn btn-primary" %>
       (in table just above)
    </p>
<% end %>

app/views/admin_public_body/_tag_help.html.erb
<h2>List of tags</h2>
<% first_row = true %>
<% for row in PublicBodyCategory.get().with_headings() %>
    <% if row.instance_of?(Array) %>
        <% if row[0] != 'other' %>
            <strong><%= row[0] %></strong>=<%= row[1] %>
            <br/>
        <% end %>
    <% elsif row != 'Miscellaneous' %>
        <% if not first_row %>
        <% else %>
            <% first_row = false %>
        <% end %>
        <h3><%=h row%></h3>
    <% end %>
<% end %>

app/views/admin_public_body/_tags.html.erb
<% for t in body.tags %>
  <span class="label label-info tag">
    <% if t.value %>
        <%= link_to(h(t.name), list_public_bodies_path(:tag => t.name)) %>:<%= link_to(h(t.value), list_public_bodies_path(:tag => t.name_and_value)) %>
    <% else %>
        <%= link_to(h(t.name), list_public_bodies_path(:tag => t.name)) %>
    <% end %>
  </span>
<% end %>

app/views/admin_public_body/edit.html.erb
<h1><%=@title%></h1>

<div class="row">
  <div class="span8">
    <div id="public_body_form">
      <%= form_for @public_body, :url => admin_body_update_path(@public_body), :html => { :class => "form form-horizontal" } do |f| %>
          <%= render :partial => 'form', :locals => {:f => f} %>
          <div class="form-actions">
            <%= f.submit 'Save', :accesskey => 's', :class => "btn btn-success" %></p>
          </div>
        <% end %>

      <div class="row">
        <div class="span8">
          <div class="well">
            <%= link_to 'Show', admin_body_show_path(@public_body), :class => "btn" %>
            <%= link_to 'List all', admin_body_list_path, :class => "btn" %>
          </div>
        </div>
      </div>

      <% if @public_body.info_requests.empty? %>
        <%= form_tag(admin_body_destroy_path(@public_body), :class => "form form-inline") do %>
         <%= hidden_field_tag(:public_body_id, { :value => @public_body.id } ) %>
         <%= submit_tag _("Destroy {{name}}", :name => @public_body.name), :class => "btn btn-danger" %> (this is permanent!)
        <% end %>
      <% end %>
    </div>

  </div>
  <div class="span4">
    <%= render :partial => 'tag_help' %>
  </div>
</div>

app/views/admin_public_body/import_csv.html.erb
<% @title = "Upload CSV of public authorities" %>

<h1><%=@title%></h1>

<% if not @notes.empty? %>
<pre id="notice"><%=@notes %></pre>
<% end %>
<% if not @errors.empty? %>
<pre id="error"><%=@errors %></pre>
<% end %>

<%= form_tag 'import_csv', :multipart => true do %>
    <p>
        <% if @original_csv_file && @temporary_csv_file %>
            CSV file:
            <%= @original_csv_file %>
            <%= hidden_field_tag :original_csv_file, @original_csv_file %>
            <%= hidden_field_tag :temporary_csv_file, @temporary_csv_file %>
            <%= link_to 'Clear current file', 'import_csv', :class => "btn btn-warning" %>
        <% else %>
            <label for="csv_file">CSV file:</label>
            <%= file_field_tag :csv_file, :size => 40 %>
        <% end %>
    </p>

    <p>
    <label for="tag">Optional: Tag to add entries to / alter entries for:</label>
    <%= text_field_tag 'tag', params[:tag] %>
    </p>

    <p>
    <label for="tag_behaviour">What to do with existing tags?</label>
    <%= select_tag 'tag_behaviour',
        raw("<option value='add' selected>Add new tags to existing ones</option>
         <option value='replace'>Replace existing tags with new ones</option>")
    %>
    </p>

    <p><strong>CSV file format:</strong> The first row should be a list
    of fields, starting with <code>#</code>. The fields <code>name</code> and
    <code>request_email</code> are required; additionally, translated values are
    supported by adding the locale name to the field name,
    e.g. <code>name.es</code>, <code>name.de</code>&hellip;<br />
    <strong>Example:</strong>
    </p>

    <pre>
&#35;name,request_email,name.es,tag_string
An Authority,a@example.com,Un organismo,a_tag another_tag
Another One,another@example.com,Otro organismo,a_tag
    </pre>

    <p><strong>Supported fields:</strong>
        <ul>
            <% PublicBody.csv_import_fields.each do |field, notes| %>
                <li><code><%= field %></code> <%= sanitize(notes) %></li>
            <% end %>
        </ul>
    </p>

    <p><strong>Note:</strong> Choose <strong>dry run</strong> to test, without
    actually altering the database. Choose <strong>upload</strong> to actually
    make the changes. In either case, you will be shown any errors, or details
    of the changes.  When uploading, any changes since last import will be
    overwritten – e.g.  email addresses changed back.
    </p>

    <p><strong>Note:</strong> The import tag will also be added to the imported bodies
    if no tags are provided in the CSV file or if the import mode is set to
    "Add new tags to existing ones".
    </p>

    <p><%= submit_tag 'Dry run' %> <%= submit_tag 'Upload' %></p>
<% end %>

<hr>

<p>Standard tags:
    <% for category, description in PublicBodyCategory.get().by_tag() %>
        <% if category != "other" %>
            <strong><%= category %></strong>=<%= description %>;
        <% end %>
    <% end %>
    </p>

app/views/admin_public_body/list.html.erb
<% if @query.nil? %>
  <% @title = _('Listing public authorities') %>
<% else %>
  <% @title = _("Listing public authorities matching '{{query}}'", :query => @query ) %>
<% end %>

<h1><%=@title%></h1>

<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to 'New public authority', admin_body_new_path, :class => "btn btn-primary" %>
  </div>
  <div class="btn-group">
    <%= link_to 'Import from CSV file', admin_body_import_csv_path, :class => "btn btn-warning" %>
  </div>
</div>

<%= form_tag({}, :method => "get", :class => "form form-search") do %>
   <%= text_field_tag 'query', params[:query], { :size => 30, :class => "input-large search-query" } %>
   <%= submit_tag "Search", :class => "btn" %>
    <% if !@query.nil? %>
      <%= link_to 'Show all', admin_body_list_path, :class => "btn" %>
    <% end %><br>
 (substring search in names and emails; exact match of tags)
<% end %>


<% if @public_bodies_by_tag.size > 0 %>
    <h2>Exact tag matches (<%= @public_bodies_by_tag.size %> total)</h2>
    <%= render :partial => 'one_list', :locals => { :bodies => @public_bodies_by_tag, :table_name => 'exact' } %>
<% end %>

<% if @public_bodies.size > 0 %>
    <% if @query.nil? %>
        <h2>All authorities</h2>
    <% else %>
        <h2>Substring search matches (<%= @public_bodies.total_entries %> total)</h2>
    <% end %>
    <%= render :partial => 'one_list', :locals => { :bodies => @public_bodies, :table_name => 'substring' } %>
<% end %>

<%= will_paginate(@public_bodies, :class => "paginator") %>

app/views/admin_public_body/missing_scheme.html.erb
<% @title = 'Popular authorities without Publication Scheme' %>

<h1><%=@title%></h1>
<p><%= @stats["entered"] %> of <%= @stats["total"] %> entered</p>

<ol>
    <% for public_body in @public_bodies %>
        <li><%= public_body_both_links(public_body) %></li>
    <% end %>
</ul>

app/views/admin_public_body/new.html.erb
<% @title = 'New public authority' %>

<h1><%=@title%></h1>
<div class="row">
  <div class="span8">
    <div id="public_body_form">
      <%= form_for @public_body, :as => :public_body, :url => admin_body_create_path, :html => {:class => "form form-horizontal"} do |f| %>
          <%= render :partial => 'form', :locals => {:f => f} %>


          <div class="form-actions">
            <%= f.submit "Create", :class => "btn btn-primary"  %>
          </div>
        <% end %>
        <div class="row">
          <div class="span8 well">
              <%= link_to 'List all', admin_body_list_path, :class => "btn" %>
          </div>
        </div>
    </div>
  </div>
  <div class="span4">
    <%= render :partial => 'tag_help' %>
  </div>
</div>

app/views/admin_public_body/show.html.erb
<% @title = _("Public authority – {{name}}", :name => h(@public_body.name)) %>

<h1><%=@title%></h1>

<table class="table table-striped table-condensed">
  <tbody>
    <% @public_body.for_admin_column do |name, value, type, column_name| %>
      <tr>
        <td>
          <b><%=name%></b>
        </td>
        <td>
          <% if ['home_page', 'publication_scheme', 'disclosure_log'].include? column_name %>
            <%= link_to(h(value), value)  %>
          <% elsif column_name == 'request_email' %>
            <%= link_to(h(value), "mailto:#{value}")  %>
              <% unless @public_body.is_requestable? %>
                <%=_("not requestable due to: {{reason}}", :reason => h(@public_body.not_requestable_reason))%><% if @public_body.is_followupable? %>; <%=_("but followupable")%><% end %>
              <% end %>
          <% else %>
              <%=h value %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        <b><%=_("Calculated home page")%></b>
      </td>
      <td>
        <% unless @public_body.calculated_home_page.nil? %>
          <%= link_to(h(@public_body.calculated_home_page), @public_body.calculated_home_page) %>
        <% else %>
          <%=_("*unknown*")%>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <b><%=_("Tags")%></b>
      </td>
      <td>
        <%= render :partial => 'tags', :locals => { :body => @public_body} %>
      </td>
    </tr>
  </tbody>
</table>
<%= link_to _("Edit"), admin_body_edit_path(@public_body), :class => "btn btn-primary" %>
<% unless @public_body.url_name.nil? %>
  <%=link_to _("Public page"), public_body_path(@public_body), :class => "btn" %>
<% else %>
  <%=_("Public page not available")%>
<% end %>
<hr>
<h2>History</h2>
<%# There may be an option to versions() to specify order, but I can't find it. TB 2009-03-09 %>
<% versions = @public_body.reverse_sorted_versions; versions.each_with_index do |historic_public_body, i| %>
  <div class="row">
    <div class="span2">
      <b>
        <%= _("Version {{version}}", :version => historic_public_body.version)%>
      </b>
    </div>
    <div class="span4">
      <%= I18n.l(historic_public_body.updated_at, :format => "%e %B %Y %H:%M:%S") %>
      (<%= _('{{length_of_time}} ago', :length_of_time => time_ago_in_words(historic_public_body.updated_at)) %>)
    </div>
    <% if i == versions.length - 1 %>
      <div class="span6">
          <p>“<%= h(historic_public_body.last_edit_comment) %>”</p>
        <ul>
          <li><%=_("This is the first version.")%></li>
        </ul>
      </div>
    <% else %>
      <div class="span6">
        <p>“<%= h(historic_public_body.last_edit_comment) %>”</p>
        <ul>
          <% historic_public_body.compare(versions[i+1]) do |change| %>
            <li><%= _("{{thing_changed}} was changed from <code>{{from_value}}</code> to <code>{{to_value}}</code>", :thing_changed => change[:name], :from_value => (change[:from] or "-"), :to_value => (change[:to] or "-")) %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>
<hr>
<h2>Requests</h2>
<%= render :partial => 'admin_request/some_requests', :locals => { :info_requests => @info_requests } %>
<%= will_paginate(@info_requests, :class => "paginator") %>
<hr>
<h2>Track things</h2>
<%= render :partial => 'admin_track/some_tracks', :locals => { :track_things => @public_body.track_things, :include_destroy => true } %>